<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/2024-06-04-dianna-multiple-linear-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from pylab import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

Marvel = pd.read_csv("https://raw.githubusercontent.com/dievikson/HypatiaAcademy/master/ml/Marvel%20Movies.csv")

In [31]:
Marvel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   movie                           36 non-null     object 
 1   category                        36 non-null     object 
 2   year                            36 non-null     int64  
 3   worldwide gross ($m)            36 non-null     int64  
 4   % budget recovered              36 non-null     object 
 5   critics % score                 36 non-null     object 
 6   audience % score                36 non-null     object 
 7   audience vs critics % deviance  36 non-null     object 
 8   budget                          36 non-null     float64
 9   domestic gross ($m)             36 non-null     int64  
 10  international gross ($m)        36 non-null     int64  
 11  opening weekend ($m)            36 non-null     float64
 12  second weekend ($m)             36 non

In [32]:
Marvel

movie         category  year  \
0                             Ant-Man            Ant-Man  2015   
1                    Ant-Man & The Wasp          Ant-Man  2018   
2               Avengers: Age of Ultron         Avengers  2015   
3                    Avengers: End Game         Avengers  2019   
4                Avengers: Infinity War         Avengers  2018   
5                         Black Panther    Black Panther  2018   
6                       Black Panther 2    Black Panther  2022   
7                           Black Widow           Unique  2021   
8                       Captain America  Captain America  2011   
9            Captain America: Civil War  Captain America  2016   
10      Captain America: Winter Soldier  Captain America  2014   
11                       Captain Marvel           Unique  2019   
12                           Dr Strange       Dr Strange  2016   
13    Dr Strange: Multiverse of Madness       Dr Strange  2022   
14                             Eternals           Unique  2021   
15              Guardians of the Galaxy        Guardians  2014   
16            Guardians of the Galaxy 2        Guardians  2017   
17                      Incredible Hulk           Unique  2008   
18                             Iron Man         Iron Man  2008   
19                           Iron Man 2         Iron Man  2010   
20                           Iron Man 3         Iron Man  2013   
21                            Shang-Chi           Unique  2021   
22            Spider-Man: Far from Home       Spider-Man  2019   
23               Spider-Man: Homecoming       Spider-Man  2017   
24              Spider-Man: No Way Home       Spider-Man  2021   
25                         The Avengers         Avengers  2012   
26                     Thor: Dark World             Thor  2013   
27                 Thor: Love & Thunder             Thor  2022   
28                       Thor: Ragnarok             Thor  2017   
29                                 Thor             Thor  2011   
30    Ant-Man and the Wasp: Quantumania          Ant-Man  2023   
31       Guardians of the Galaxy Vol. 3        Guardians  2023   
32                          The Marvels           Unique  2023   
33  Spider-Man: Across the Spider-Verse       Spider-Man  2023   
34                             Deadpool         Deadpool  2016   
35                           Deadpool 2         Deadpool  2018   

    worldwide gross ($m) % budget recovered critics % score audience % score  \
0                    518               398%             83%              85%   
1                    623               479%             87%              80%   
2                   1395               382%             76%              82%   
3                   2797               699%             94%              90%   
4                   2048               683%             85%              91%   
5                   1336               668%             96%              79%   
6                    855               342%             84%              94%   
7                    379               190%             79%              80%   
8                    370               264%             79%              75%   
9                   1151               460%             90%              89%   
10                   714               420%             90%              92%   
11                  1129               645%             79%              45%   
12                   676               410%             89%              86%   
13                   952               476%             74%              77%   
14                   402               201%             47%              73%   
15                   770               453%             92%              92%   
16                   869               435%             85%              87%   
17                   265               193%             67%              69%   
18                   585               315%             94%            

In [33]:
Marvel.dropna(axis=1,inplace=True)

In [34]:
Marvel.columns

Index(['movie', 'category', 'year', 'worldwide gross ($m)',
       '% budget recovered', 'critics % score', 'audience % score',
       'audience vs critics % deviance', 'budget', 'domestic gross ($m)',
       'international gross ($m)', 'opening weekend ($m)',
       'second weekend ($m)', '1st vs 2nd weekend drop off',
       '% gross from opening weekend', '% gross from domestic',
       '% gross from international', '% budget opening weekend'],
      dtype='object')

In [35]:
Marvel

movie         category  year  \
0                             Ant-Man            Ant-Man  2015   
1                    Ant-Man & The Wasp          Ant-Man  2018   
2               Avengers: Age of Ultron         Avengers  2015   
3                    Avengers: End Game         Avengers  2019   
4                Avengers: Infinity War         Avengers  2018   
5                         Black Panther    Black Panther  2018   
6                       Black Panther 2    Black Panther  2022   
7                           Black Widow           Unique  2021   
8                       Captain America  Captain America  2011   
9            Captain America: Civil War  Captain America  2016   
10      Captain America: Winter Soldier  Captain America  2014   
11                       Captain Marvel           Unique  2019   
12                           Dr Strange       Dr Strange  2016   
13    Dr Strange: Multiverse of Madness       Dr Strange  2022   
14                             Eternals           Unique  2021   
15              Guardians of the Galaxy        Guardians  2014   
16            Guardians of the Galaxy 2        Guardians  2017   
17                      Incredible Hulk           Unique  2008   
18                             Iron Man         Iron Man  2008   
19                           Iron Man 2         Iron Man  2010   
20                           Iron Man 3         Iron Man  2013   
21                            Shang-Chi           Unique  2021   
22            Spider-Man: Far from Home       Spider-Man  2019   
23               Spider-Man: Homecoming       Spider-Man  2017   
24              Spider-Man: No Way Home       Spider-Man  2021   
25                         The Avengers         Avengers  2012   
26                     Thor: Dark World             Thor  2013   
27                 Thor: Love & Thunder             Thor  2022   
28                       Thor: Ragnarok             Thor  2017   
29                                 Thor             Thor  2011   
30    Ant-Man and the Wasp: Quantumania          Ant-Man  2023   
31       Guardians of the Galaxy Vol. 3        Guardians  2023   
32                          The Marvels           Unique  2023   
33  Spider-Man: Across the Spider-Verse       Spider-Man  2023   
34                             Deadpool         Deadpool  2016   
35                           Deadpool 2         Deadpool  2018   

    worldwide gross ($m) % budget recovered critics % score audience % score  \
0                    518               398%             83%              85%   
1                    623               479%             87%              80%   
2                   1395               382%             76%              82%   
3                   2797               699%             94%              90%   
4                   2048               683%             85%              91%   
5                   1336               668%             96%              79%   
6                    855               342%             84%              94%   
7                    379               190%             79%              80%   
8                    370               264%             79%              75%   
9                   1151               460%             90%              89%   
10                   714               420%             90%              92%   
11                  1129               645%             79%              45%   
12                   676               410%             89%              86%   
13                   952               476%             74%              77%   
14                   402               201%             47%              73%   
15                   770               453%             92%              92%   
16                   869               435%             85%              87%   
17                   265               193%             67%              69%   
18                   585               315%             94%            

In [36]:
movies = Marvel[['critics % score', '% budget recovered','1st vs 2nd weekend drop off']].copy()

In [37]:
movies.columns = ['y', 'x1', 'x2']

In [38]:
movies

y     x1    x2
0   83%   398%  -58%
1   87%   479%  -62%
2   76%   382%  -60%
3   94%   699%  -59%
4   85%   683%  -56%
5   96%   668%  -45%
6   84%   342%  -64%
7   79%   190%  -68%
8   79%   264%  -62%
9   90%   460%  -59%
10  90%   420%  -57%
11  79%   645%  -56%
12  89%   410%  -50%
13  74%   476%  -67%
14  47%   201%  -62%
15  92%   453%  -55%
16  85%   435%  -55%
17  67%   193%  -60%
18  94%   315%  -50%
19  71%   365%  -59%
20  79%   608%  -58%
21  91%   288%  -54%
22  90%   708%  -51%
23  92%   502%  -62%
24  93%   956%  -68%
25  91%   673%  -50%
26  66%   429%  -57%
27  64%   298%  -68%
28  93%   472%  -53%
29  77%   299%  -48%
30  47%   190%  -69%
31  82%   338%  -59%
32  57%   201%  -67%
33  96%   681%  -57%
34  85%  1350%  -57%
35  84%   714%  -65%

In [39]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   y       36 non-null     object
 1   x1      36 non-null     object
 2   x2      36 non-null     object
dtypes: object(3)
memory usage: 992.0+ bytes


In [40]:
Marvel.columns

Index(['movie', 'category', 'year', 'worldwide gross ($m)',
       '% budget recovered', 'critics % score', 'audience % score',
       'audience vs critics % deviance', 'budget', 'domestic gross ($m)',
       'international gross ($m)', 'opening weekend ($m)',
       'second weekend ($m)', '1st vs 2nd weekend drop off',
       '% gross from opening weekend', '% gross from domestic',
       '% gross from international', '% budget opening weekend'],
      dtype='object')

In [41]:
y = Marvel.iloc[:,-1].values


In [42]:
import re

def toNumber(n):

    s=re.sub(r'[^\d\.]+', '', n)
    i=int(s)
    return i/100


In [43]:
toNumber("-45%")

0.45

In [44]:
movies

y     x1    x2
0   83%   398%  -58%
1   87%   479%  -62%
2   76%   382%  -60%
3   94%   699%  -59%
4   85%   683%  -56%
5   96%   668%  -45%
6   84%   342%  -64%
7   79%   190%  -68%
8   79%   264%  -62%
9   90%   460%  -59%
10  90%   420%  -57%
11  79%   645%  -56%
12  89%   410%  -50%
13  74%   476%  -67%
14  47%   201%  -62%
15  92%   453%  -55%
16  85%   435%  -55%
17  67%   193%  -60%
18  94%   315%  -50%
19  71%   365%  -59%
20  79%   608%  -58%
21  91%   288%  -54%
22  90%   708%  -51%
23  92%   502%  -62%
24  93%   956%  -68%
25  91%   673%  -50%
26  66%   429%  -57%
27  64%   298%  -68%
28  93%   472%  -53%
29  77%   299%  -48%
30  47%   190%  -69%
31  82%   338%  -59%
32  57%   201%  -67%
33  96%   681%  -57%
34  85%  1350%  -57%
35  84%   714%  -65%

In [45]:
movies['x2']=movies['x2'].apply(toNumber)
movies['x1']=movies['x1'].apply(toNumber)
movies['y']=movies['y'].apply(toNumber)

In [46]:
movies

y     x1    x2
0   0.83   3.98  0.58
1   0.87   4.79  0.62
2   0.76   3.82  0.60
3   0.94   6.99  0.59
4   0.85   6.83  0.56
5   0.96   6.68  0.45
6   0.84   3.42  0.64
7   0.79   1.90  0.68
8   0.79   2.64  0.62
9   0.90   4.60  0.59
10  0.90   4.20  0.57
11  0.79   6.45  0.56
12  0.89   4.10  0.50
13  0.74   4.76  0.67
14  0.47   2.01  0.62
15  0.92   4.53  0.55
16  0.85   4.35  0.55
17  0.67   1.93  0.60
18  0.94   3.15  0.50
19  0.71   3.65  0.59
20  0.79   6.08  0.58
21  0.91   2.88  0.54
22  0.90   7.08  0.51
23  0.92   5.02  0.62
24  0.93   9.56  0.68
25  0.91   6.73  0.50
26  0.66   4.29  0.57
27  0.64   2.98  0.68
28  0.93   4.72  0.53
29  0.77   2.99  0.48
30  0.47   1.90  0.69
31  0.82   3.38  0.59
32  0.57   2.01  0.67
33  0.96   6.81  0.57
34  0.85  13.50  0.57
35  0.84   7.14  0.65

In [47]:
m=movies.to_numpy()
m

array([[ 0.83,  3.98,  0.58],
       [ 0.87,  4.79,  0.62],
       [ 0.76,  3.82,  0.6 ],
       [ 0.94,  6.99,  0.59],
       [ 0.85,  6.83,  0.56],
       [ 0.96,  6.68,  0.45],
       [ 0.84,  3.42,  0.64],
       [ 0.79,  1.9 ,  0.68],
       [ 0.79,  2.64,  0.62],
       [ 0.9 ,  4.6 ,  0.59],
       [ 0.9 ,  4.2 ,  0.57],
       [ 0.79,  6.45,  0.56],
       [ 0.89,  4.1 ,  0.5 ],
       [ 0.74,  4.76,  0.67],
       [ 0.47,  2.01,  0.62],
       [ 0.92,  4.53,  0.55],
       [ 0.85,  4.35,  0.55],
       [ 0.67,  1.93,  0.6 ],
       [ 0.94,  3.15,  0.5 ],
       [ 0.71,  3.65,  0.59],
       [ 0.79,  6.08,  0.58],
       [ 0.91,  2.88,  0.54],
       [ 0.9 ,  7.08,  0.51],
       [ 0.92,  5.02,  0.62],
       [ 0.93,  9.56,  0.68],
       [ 0.91,  6.73,  0.5 ],
       [ 0.66,  4.29,  0.57],
       [ 0.64,  2.98,  0.68],
       [ 0.93,  4.72,  0.53],
       [ 0.77,  2.99,  0.48],
       [ 0.47,  1.9 ,  0.69],
       [ 0.82,  3.38,  0.59],
       [ 0.57,  2.01,  0.67],
       [ 0

In [48]:
y=m[:,0]

y

array([0.83, 0.87, 0.76, 0.94, 0.85, 0.96, 0.84, 0.79, 0.79, 0.9 , 0.9 ,
       0.79, 0.89, 0.74, 0.47, 0.92, 0.85, 0.67, 0.94, 0.71, 0.79, 0.91,
       0.9 , 0.92, 0.93, 0.91, 0.66, 0.64, 0.93, 0.77, 0.47, 0.82, 0.57,
       0.96, 0.85, 0.84])

In [49]:

x1x2=m[:,1:3]
x1x2

array([[ 3.98,  0.58],
       [ 4.79,  0.62],
       [ 3.82,  0.6 ],
       [ 6.99,  0.59],
       [ 6.83,  0.56],
       [ 6.68,  0.45],
       [ 3.42,  0.64],
       [ 1.9 ,  0.68],
       [ 2.64,  0.62],
       [ 4.6 ,  0.59],
       [ 4.2 ,  0.57],
       [ 6.45,  0.56],
       [ 4.1 ,  0.5 ],
       [ 4.76,  0.67],
       [ 2.01,  0.62],
       [ 4.53,  0.55],
       [ 4.35,  0.55],
       [ 1.93,  0.6 ],
       [ 3.15,  0.5 ],
       [ 3.65,  0.59],
       [ 6.08,  0.58],
       [ 2.88,  0.54],
       [ 7.08,  0.51],
       [ 5.02,  0.62],
       [ 9.56,  0.68],
       [ 6.73,  0.5 ],
       [ 4.29,  0.57],
       [ 2.98,  0.68],
       [ 4.72,  0.53],
       [ 2.99,  0.48],
       [ 1.9 ,  0.69],
       [ 3.38,  0.59],
       [ 2.01,  0.67],
       [ 6.81,  0.57],
       [13.5 ,  0.57],
       [ 7.14,  0.65]])

In [50]:
# when you want do to a prediction and you have 1,000 data samples.  the normal procedure
# is to take maybe 40% to use to train the model.  train means find the coefficients.
# that means find m1 m2 ...

# and then you use the remaining part to test it.  test it means to see how accurate it is.




#xtrain,xtest=np.array_split(x, 2)
#ytrain,ytest=np.array_split(y, 2)


reg = LinearRegression()
reg.fit(x1x2, y)

# linear regression solves this for m1 and m2

# y = m1 * x1 + m2 * x2 + b

# this is our predictive model


LinearRegression()

In [51]:
np.set_printoptions(suppress=True, precision=10)

print('Coefficients: \n', reg.coef_)
print('\n Intercept: \n', reg.intercept_)


Coefficients: 
 [ 0.0222460491 -0.9080425153]

 Intercept: 
 1.2385964518236987


In [52]:
# means we IF this model is correct then we estimate the 'critics % score',  on:

# '% budget recovered','1st vs 2nd weekend drop off

# 'critics % score' = y
# '% budget recovered' = x1
# '1st vs 2nd weekend drop off'

# y = 0.0222460491 * x1 -0.9080425153 * x2 +  1.2385964518236987


In [53]:
lastRow = [ 0.84,  7.14,  0.65]

# these are the coefficients that the linear regression algorithm found:
# reg = LinearRegression()<----create the model or the algorithm
# reg.fit(x1x2, y)<----fit a line, or find the that goes down the middle
# using the least square errors technique


m1 = 0.0222460491
m2 = -0.9080425153
b = 1.2385964518236987


x1 = 7.14
x2 = 0.65

ypred= m1 * x1 + m2 * x2 + b
ypred

0.8072056074526986

In [54]:
# Make predictions
y_pred = reg.predict(x1x2)

# Calculate R-squared
r2 = r2_score(y, y_pred)
print(f"R-squared: {r2}")



R-squared: 0.43339908115527415


In [55]:
y

array([0.83, 0.87, 0.76, 0.94, 0.85, 0.96, 0.84, 0.79, 0.79, 0.9 , 0.9 ,
       0.79, 0.89, 0.74, 0.47, 0.92, 0.85, 0.67, 0.94, 0.71, 0.79, 0.91,
       0.9 , 0.92, 0.93, 0.91, 0.66, 0.64, 0.93, 0.77, 0.47, 0.82, 0.57,
       0.96, 0.85, 0.84])

In [56]:
# b is y intercept when we have one variable x and we are solving simple linear regression

# which is y = mx + b

# b is the point on the graph (b,0)
# this is the y intercept


In [59]:
import statsmodels.api as sm

# Add a constant to the model (intercept)
X_train_sm = sm.add_constant(x1x2)

# Fit the model using statsmodels
model_sm = sm.OLS(y, X_train_sm).fit()

# Print the summary to get p-values, R-squared, and other statistics
print(model_sm.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.433
Model:                            OLS   Adj. R-squared:                  0.399
Method:                 Least Squares   F-statistic:                     12.62
Date:                Sat, 01 Jun 2024   Prob (F-statistic):           8.49e-05
Time:                        04:52:32   Log-Likelihood:                 33.665
No. Observations:                  36   AIC:                            -61.33
Df Residuals:                      33   BIC:                            -56.58
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.2386      0.174      7.114      0.0