<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/2024_06_04_lr_get_data_ready.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/Annepikson/HypatiaAcademy/master/ml/Top_200_Movies_Dataset_2023(Cleaned).csv")
df


# we want to make a prediction,  we a model that give some inputs x1, x2, x3, ...  we can predict y

# Warner bros movies are highly ranked

# ranking is related to gross sales


#y=rank

#x1=total gross

#x=distributor


Rank                                      Title Theaters   Total Gross  \
0       1                                     Barbie    4,337  $594,254,460   
1       2                The Super Mario Bros. Movie    4,371  $574,759,600   
2       3        Spider-Man: Across the Spider-Verse    4,332  $381,178,195   
3       4             Guardians of the Galaxy Vol. 3    4,450  $358,995,815   
4       5                                Oppenheimer    3,761  $300,144,670   
..    ...                                        ...      ...           ...   
195   196  Contempt4k Restoration - 60th Anniversary        8      $173,816   
196   197                         The Wrath of Becky      274      $168,109   
197   198                          The Starling Girl      114      $161,290   
198   199                          ¡Que viva México!       90      $161,222   
199   200                                   Enys Men       62      $189,579   

            Release Date                          Distributor  
0    2023-07-21 00:00:00                         Warner Bros.  
1    2023-04-05 00:00:00                   Universal Pictures  
2    2023-06-02 00:00:00                    Columbia Pictures  
3    2023-05-05 00:00:00  Walt Disney Studios Motion Pictures  
4    2023-07-21 00:00:00                   Universal Pictures  
..                   ...                                  ...  
195  2023-06-30 00:00:00                      Rialto Pictures  
196  2023-05-26 00:00:00                  Quiver Distribution  
197  2023-05-12 00:00:00                Bleecker Street Media  
198  2023-03-24 00:00:00    Sony Pictures Entertainment (SPE)  
199  2023-03-31 00:00:00                                   '-  

[200 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Rank          200 non-null    int64 
 1   Title         200 non-null    object
 2   Theaters      200 non-null    object
 3   Total Gross   200 non-null    object
 4   Release Date  200 non-null    object
 5   Distributor   200 non-null    object
dtypes: int64(1), object(5)
memory usage: 9.5+ KB


In [9]:



import re

a = "$594,254,460"

#s=re.sub(r'[\d\.]+', '', a)

s=a.replace('$', '')
t=s.replace(',', '')
int(t)



594254460

In [11]:
import re


def tonumber(n):

  s=n.replace('$', '')
  t=s.replace(',', '')
  return int(t)



In [12]:
tonumber("$555,222,111")

555222111

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x2=le.fit_transform(df['Distributor'])

x2

array([49, 44, 10, 48, 44, 48,  1, 48, 20,  3, 48, 28, 28, 43, 48, 44, 44,
       28, 49, 28, 44, 28, 34, 49, 49, 44, 10, 48, 49,  0, 20, 40, 49, 48,
        2, 28, 44, 40, 20, 40, 14, 49, 20, 34, 40, 20, 14, 51, 48, 44, 23,
       44, 14, 12, 28, 44, 20,  2, 20,  3, 11,  2, 40, 42, 11, 49,  2,  2,
       20,  0, 20, 41, 28, 34, 44, 13, 38, 40, 43, 24,  2, 25, 18, 25, 47,
       49, 33,  0, 13, 35, 13, 48,  5, 50, 14, 44, 36, 39, 35,  7, 51, 13,
       43, 33, 40, 17, 44,  5, 33,  5, 13, 16,  8, 11, 35, 14, 24, 17, 13,
        0, 46, 41, 15, 14, 17, 13, 48,  2,  5,  0, 24,  2,  9, 14, 33, 17,
       39, 50,  0, 13,  0, 47, 40, 10, 22, 39, 17, 37, 13, 13, 13, 14,  7,
        2, 17,  0, 26, 24, 39, 13, 39,  4,  6, 27, 30,  0,  0, 40, 29,  0,
        0,  0, 11,  0, 13, 27, 21,  0,  6, 33, 45, 14, 35, 50, 45,  0,  0,
       24, 37, 40, 13,  2,  0, 40, 19, 32, 31,  5, 40,  0])

In [31]:

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from pylab import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [18]:
y=df['Rank'].values


numpy.ndarray

In [21]:
x1=df['Total Gross'].apply(tonumber)

In [27]:
# use capital letters when dealing arrays that has more than one dimension
import numpy as np

X=np.column_stack((x1,x2))
X

array([[594254460,        49],
       [574759600,        44],
       [381178195,        10],
       [358995815,        48],
       [300144670,        44],
       [297895447,        48],
       [684075767,         1],
       [214504909,        48],
       [187131806,        20],
       [180587629,         3],
       [174116627,        48],
       [168248955,        28],
       [157066392,        28],
       [156248615,        43],
       [151692473,        48],
       [145960660,        44],
       [185535345,        44],
       [108161389,        28],
       [108133313,        49],
       [ 99847538,        28],
       [ 95043350,        44],
       [ 93277026,        28],
       [ 82042800,        34],
       [ 74469810,        49],
       [ 67233054,        49],
       [ 64388510,        44],
       [ 64267657,        10],
       [ 62291150,        48],
       [ 57638006,        49],
       [ 52460106,         0],
       [ 52102987,        20],
       [ 50452282,        40],
       [

In [28]:
X.shape

(200, 2)

In [29]:
y.shape

(200,)

In [39]:
X

array([[594254460,        49],
       [574759600,        44],
       [381178195,        10],
       [358995815,        48],
       [300144670,        44],
       [297895447,        48],
       [684075767,         1],
       [214504909,        48],
       [187131806,        20],
       [180587629,         3],
       [174116627,        48],
       [168248955,        28],
       [157066392,        28],
       [156248615,        43],
       [151692473,        48],
       [145960660,        44],
       [185535345,        44],
       [108161389,        28],
       [108133313,        49],
       [ 99847538,        28],
       [ 95043350,        44],
       [ 93277026,        28],
       [ 82042800,        34],
       [ 74469810,        49],
       [ 67233054,        49],
       [ 64388510,        44],
       [ 64267657,        10],
       [ 62291150,        48],
       [ 57638006,        49],
       [ 52460106,         0],
       [ 52102987,        20],
       [ 50452282,        40],
       [

In [40]:
y

-76.77361344617856

In [32]:
reg = LinearRegression()
reg.fit(X, y)

LinearRegression()

In [33]:
np.set_printoptions(suppress=True, precision=10)

print('Coefficients: \n', reg.coef_)
print('\n Intercept: \n', reg.intercept_)



Coefficients: 
 [-0.0000002863 -0.7538366995]

 Intercept: 
 130.29943672732145


In [34]:
#. y = m1x1 + m2x2 + b

x1, x2 = [594254460,        49]


# so our linear regression model said that the movie rank (y) can be approximated by this formula

# m1 = -0.0000002863
# m2 = -0.7538366995

# for every x1 and every x2

y = -0.0000002863 * x1 -0.7538366995 * x2 + 130.29943672732145


In [35]:
y

-76.77361344617856

# to test this we would do a lot


now we have our model.  we have to ask:  is it correct?  is it logical?

draw a chart

R-score



# Homework

Our hypothese is that life expectancy (how long will you live) is
corelated with

* y =

* Alcohol make that me x1

* life expectancy

* x2 = Diphtheria

* x3 = under-five deaths

* x4 = percentage expenditure

* x5 = Status (use labeleconder)


```
'Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling']
  ```

In [37]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/werowe/HypatiaAcademy/master/ml/Life%20Expectancy%20Data.csv")

df




Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0   
1     Afghanistan  2014  Developing              59.9            271.0   
2     Afghanistan  2013  Developing              59.9            268.0   
3     Afghanistan  2012  Developing              59.5            272.0   
4     Afghanistan  2011  Developing              59.2            275.0   
...           ...   ...         ...               ...              ...   
2933     Zimbabwe  2004  Developing              44.3            723.0   
2934     Zimbabwe  2003  Developing              44.5            715.0   
2935     Zimbabwe  2002  Developing              44.8             73.0   
2936     Zimbabwe  2001  Developing              45.3            686.0   
2937     Zimbabwe  2000  Developing              46.0            665.0   

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154   
1                64     0.01               73.523582         62.0       492   
2                66     0.01               73.219243         64.0       430   
3                69     0.01               78.184215         67.0      2787   
4                71     0.01                7.097109         68.0      3013   
...             ...      ...                     ...          ...       ...   
2933             27     4.36                0.000000         68.0        31   
2934             26     4.06                0.000000          7.0       998   
2935             25     4.43                0.000000         73.0       304   
2936             25     1.72                0.000000         76.0       529   
2937             24     1.68                0.000000         79.0      1483   

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210   
1     ...   58.0               8.18         62.0        0.1  612.696514   
2     ...   62.0               8.13         64.0        0.1  631.744976   
3     ...   67.0               8.52         67.0        0.1  669.959000   
4     ...   68.0               7.87         68.0        0.1   63.537231   
...   ...    ...                ...          ...        ...         ...   
2933  ...   67.0               7.13         65.0       33.6  454.366654   
2934  ...    7.0               6.52         68.0       36.7  453.351155   
2935  ...   73.0               6.53         71.0       39.8   57.348340   
2936  ...   76.0               6.16         75.0       42.1  548.587312   
2937  ...   78.0               7.10         78.0       43.5  547.358878   

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3   
1       327582.0                   17.5                 17.5   
2     31731688.0                   17.7                 17.7   
3      3696958.0                   17.9                 18.0   
4      2978599.0                   18.2                 18.2   
...          ...                    ...                  ...   
2933  12777511.0                    9.4                  9.4   
2934  12633897.0                    9.8                  9.9   
2935    125525.0                    1.2                  1.3   
2936  12366165.0                    1.6                  1.7   
2937  12222251.0                   11.0                 11.2   

      Income composition of resources  Schooling  
0                               0.479       10.1  
1                               0.476       10.0  
2                               0.470        9.9  
3                               0.463        9.8  
4                               0.454        9.5  
...                               ...        ...  
2933                            0.407        9.2  
2934                            0.418        9.5  
2935                            0.427      

In [38]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')