<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/2024_07_09_AND_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# AND

# we want to solve AND problem.  Meaning we want to solve A AND B is true or false
# for every possible combination or A FALSE, TRUE



# HOMEWORK

#convert this to solve the OR problem

# A OR B = TRUE

# this means design the inputs to represent all 4 possibilites using OR instead of AND





| A | B | true or false|
| ---- | --- | ---- |
| 1   | 1    |  1       |
| 0   | 0    |  0       |
| 1   | 0    |  0       |
| 0   | 1    |  0       |




In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np



inputs = np.array([[1,1],
                   [0,0],
                  [1,0],
                   [0,1]])

# features and labels

labels = np.array([[1],
                   [0],
                  [0],
                   [0]])



# input layer , it will do some calculation.  it will take the input and output some values
# output layer will take data from the input layer and output a single value

# what is error?  predicted value - observed value

# there's two layers.  because I have two lines below

# input is the array.  you have to give it the shape
# second layer is the output.  that will be a single value: true or false 1 or 0


# 4 here does not mean 4 layers.  it is a parameter.  picking the right number is adjusting the
# parameter.  it has to do with the size of the nueral network.  so there is no correct way to do
# that.  however if you the number too small then your answer could be wrong.


# activation function

# relu is y=max(0,x)
# looks like it will get rid of all negative numbers
# y = max(0,2)

# activation functions something don't make much sense
# they are designed so that there is non-linearity in the network

# y = 2 * x
# that would not solve neural networks that are not linear


# the range of a function means what range are the possible values.  range of max(0,x) is (0, infinity)
# domain means what can you put into it.  answer:  (-infinity, infinity)

# sigmoid generates a probability. (0,1)
# this means this is going to not calulate true of false.  it's going to calcualte the probability
# that the answer is true or false
# with logistic regression if p(x) >= 0.5 then TRUE


model = keras.Sequential([
    Dense(4, activation="relu", input_shape=(2,)),  # Correct input shape
    Dense(1, activation="sigmoid")  # One output neuron with sigmoid activation
])


# when we did linear regression then that meant minimize the MSE
# we could have also said maximize the accuracy

# we are using calculus.  in calculation you what what are called limits.
# that means get very close to something, but never exactly the then
# 0.999999999999999


# we will we use : binary_crossentropy
# why?
# because 1.  it's binary because it has two possible values 1 or
# crossentropy means check each output against each node.  check all possibilities

# here we have a very small training set you can use sparse_binary_crossentropy


# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# epoch means how many times to rerun
# it's looking for maximum accuracy (= minimum error)
# it changes the weights in very small increments
# we say it converges that means it finds a solution when the error is almost 0


# Train the model
model.fit(inputs, labels, epochs=10000, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(inputs, labels, verbose=0)
print(f"Accuracy: {accuracy*100:.2f}%")


Accuracy: 100.00%


In [15]:
#model.predict([1,1])

predictions=model.predict(inputs)

np.set_printoptions(suppress=True)

np.column_stack([labels,predictions])

1/1 [==============================] - 0s 34ms/step


array([[1.        , 0.99979693],
       [0.        , 0.00000688],
       [0.        , 0.00015933],
       [0.        , 0.00639563]])

In [17]:
# Apply threshold to convert probabilities to class labels
predicted_classes = (predictions > 0.5).astype(int)
print("\n Predictions:")
print(predicted_classes)


print("\n inputs, labels, predicted %, predicted 1 or 0")
np.column_stack([inputs[:4], labels[:4],predictions,predicted_classes])


 Predictions:
[[1]
 [0]
 [0]
 [0]]

 inputs, labels, predicted %, predicted 1 or 0


array([[1.        , 1.        , 1.        , 0.99979693, 1.        ],
       [0.        , 0.        , 0.        , 0.00000688, 0.        ],
       [1.        , 0.        , 0.        , 0.00015933, 0.        ],
       [0.        , 1.        , 0.        , 0.00639563, 0.        ]])

In [20]:
(predictions > 0.5).astype(int)

array([[1],
       [0],
       [0],
       [0]])

In [16]:
inputs[0]

array([1, 1])

In [ ]:
# remember when I say do 10,000 epochs

# that means do linear algebra mutplication x and weights and bias

# remeber than matrix multication can be broken apart and done simultaneoulsy
# a cpu can only 1 thing at a time per core


# Loss Function
A loss function is a mathematical function used in machine learning to measure the difference between the predicted output of a model and the actual target values


In [7]:
inputs[0]

array([1, 1])