<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/2024-06-21-logistic-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
pima=pd.read_csv("https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv")

pima

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [6]:
pima

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [7]:
pima.index

RangeIndex(start=0, stop=768, step=1)

In [8]:
pima.dropna(inplace=True)


In [9]:
a = pima.to_numpy()
y=a[:,-1]


In [10]:
a.shape

(768, 9)

In [11]:
X=a[:,:-1]
X.shape

(768, 8)

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from pylab import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [13]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

In [14]:
xtrain.shape

(614, 8)

In [15]:
xtest.shape

(154, 8)

In [18]:
# create model

model = LogisticRegression()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# train model.  which means calculate coefficients and y-intercept

model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)

model.fit(xtrain, ytrain)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [19]:
# Extract coefficients and intercept
print("Coefficients:")
print(model.coef_)
print("\nIntercept:")
print(model.intercept_)


Coefficients:
[[ 0.14095134  0.03413061 -0.01369654  0.00378721 -0.00162575  0.08965722
   0.6373274   0.00890897]]

Intercept:
[-7.88954467]


In [27]:
g = np.array([1,2,3])
g.ndim

1

In [23]:
# how can I manually do this prediction.  just multiply the coefficients times the first test row
m=model.coef_.shape




AttributeError: 'tuple' object has no attribute 'ndim'

In [29]:
j=np.array([[ 0.14095134 , 0.03413061 ,-0.01369654  ,0.00378721 ,-0.00162575,  0.08965722,
   0.6373274  , 0.00890897]])

# first coefficient

j[0,0]


0.14095134

In [33]:
xtest[0,0]


1.0

In [34]:
xtest[0,:]

array([  1.   , 112.   ,  72.   ,  30.   , 176.   ,  34.4  ,   0.528,
        25.   ])

In [40]:
firstpred=np.matmul(model.coef_,xtest[0,:]) + model.intercept_
firstpred

# this number is not a number like 2 or 3.  remember it's this formula:

# logistic regression formular

import math

1 / (1 + math.e**-firstpred)


# rule is if logistic regression number > 0.5 then you say 1
# otherwise it's 0



array([0.19136125])

In [42]:
pima.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [36]:
# show the coefficients

preds=model.predict(xtest)


In [41]:
xtest[0]

array([  1.   , 112.   ,  72.   ,  30.   , 176.   ,  34.4  ,   0.528,
        25.   ])

In [38]:
preds[0]

0.0

In [44]:
# what is accuracy?
# remember shooting bow and arrow.  you either hit the target 1 or you miss 0

#shots = [1,1,0,1,0]

#accuracy = number of correct answers / number of TRAITLETS_APPLICATION_RAISE_CONFIG_FILE_ERROR

#3/5
#shots = [1,1,1,1,1]

#5/5
#100%


# accuracy of our model is what?

# preds is our prediction

# ytest is 20% of our data


preds[0],ytest[0]

#data=checking
#data[data[:, 15] != data[:, 16]].shape

(0.0, 0.0)

In [52]:
ytest.shape

(154,)

In [51]:
d=np.column_stack([preds,ytest])

# how do we get a count of correct answers?

correct=d[d[:,0] == d[:,1]]

correct.shape



(122, 2)

In [53]:
ytest.shape[0]



154

In [54]:
correct.shape[0]

122

In [56]:
# accuracy = count  of correct things / count of all things




accuracy = correct.shape[0] / ytest.shape[0]
accuracy

0.7922077922077922

In [57]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Calculate the accuracy score
accuracy = accuracy_score(ytest, preds)
print("Accuracy:", accuracy)



Accuracy: 0.7922077922077922


In [59]:
# Calculate other metrics

# homework.  read about what is precision.  write a description of me of what is precision.

# if you can write a definition of recall and f1_score

# confusion matrix we will do together

# interpret the sections .  it says precision = 0.64.  Is that good?


precision = precision_score(ytest, preds)
recall = recall_score(ytest, preds)
f1 = f1_score(ytest, preds)
confusion = confusion_matrix(ytest, preds)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("\nConfusion Matrix:\n", confusion)

Precision: 0.6428571428571429
Recall: 0.6136363636363636
F1-score: 0.6279069767441862

Confusion Matrix:
 [[95 15]
 [17 27]]
