<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/convert_perceptron_to_AND_classification_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Correct inputs for the AND problem
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

# Correct labels for the AND problem
labels = np.array([0, 0, 0, 1])

# Define the model
model = keras.Sequential([
    Dense(4, activation="relu", input_shape=(2,)),  # Correct input shape
    Dense(1, activation="sigmoid")  # One output neuron with sigmoid activation
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(inputs, labels, epochs=100, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(inputs, labels, verbose=0)
print(f"Accuracy: {accuracy*100:.2f}%")

# Predict with the model
predictions = model.predict(inputs)
print("Predictions:")
print(predictions)


Accuracy: 75.00%
1/1 [==============================] - 0s 41ms/step
Predictions:
[[0.47549886]
 [0.2795016 ]
 [0.47549886]
 [0.47549886]]


In [24]:
# Try with more data.  Copy the data onto itself

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Original inputs and labels
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

labels = np.array([0, 0, 0, 1])

# Duplicate the dataset
inputs = np.tile(inputs, (100, 1))
labels = np.tile(labels, 100)

# Define the model
model = keras.Sequential([
    Dense(4, activation="relu", input_shape=(2,)),
    Dense(1, activation="sigmoid")
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(inputs, labels, epochs=100, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(inputs[:4], labels[:4], verbose=0)
print(f"Accuracy: {accuracy*100:.2f}%")

# Predict with the model
predictions = model.predict(inputs[:4])
print("Predictions:")
print(predictions)

# Apply threshold to convert probabilities to class labels
predicted_classes = (predictions > 0.5).astype(int)
print("\n Predictions:")
print(predicted_classes)


print("\n inputs, labels, predicted %, predicted 1 or 0")
np.column_stack([inputs[:4], labels[:4],predictions,predicted_classes])


Accuracy: 100.00%
1/1 [==============================] - 0s 72ms/step
Predictions:
[[0.17339316]
 [0.2736015 ]
 [0.10613744]
 [0.77932256]]

 Predictions:
[[0]
 [0]
 [0]
 [1]]

 inputs, labels, predicted %, predicted 1 or 0


array([[0.        , 0.        , 0.        , 0.17339316, 0.        ],
       [0.        , 1.        , 0.        , 0.2736015 , 0.        ],
       [1.        , 0.        , 0.        , 0.10613744, 0.        ],
       [1.        , 1.        , 1.        , 0.77932256, 1.        ]])