<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#A Perceptron Illustrated
Perceptron consists of a single layer of input nodes that are fully connected to a layer of output nodes.


$$output=activationfunction(weights * inputs+bias)$$


#The AND Problem
| A      | B      | XOR |
| ------------- | ------------- |  ------------- |
| 1| 1 | 1 |
| 0| 1| 0 |
| 1 | 0 | 0 |
| 0| 0 | 0 |






![](https://miro.medium.com/v2/resize:fit:1400/format:webp/0*Ib3_FfuOy04kOmfO)

Image credit:
[Muneeb S. Ahma](https://muneebsa.medium.com/deep-learning-101-lesson-7-perceptron-f6a698d81be8)

In [11]:
import numpy as np

# Define the perceptron for the AND problem
class PerceptronAND:
    def __init__(self, lr=0.1, epochs=1000):
        self.lr = lr
        self.epochs = epochs
        self.weights = np.random.uniform(-0.1, 0.1, 3)  # 2 weights for inputs, 1 for bias
        self.bias = 1

    def activation(self, x):
        return 1 if x > 0 else 0

    def train(self, inputs, outputs):
        for epoch in range(self.epochs):
            total_error = 0
            for x, target in zip(inputs, outputs):
                # Compute weighted sum (including bias)
                weighted_sum = np.dot(x, self.weights[:2]) + self.bias * self.weights[2]
                prediction = self.activation(weighted_sum)
                error = target - prediction
                total_error += abs(error)
                # Update weights and bias
                self.weights[:2] += self.lr * error * x
                self.weights[2] += self.lr * error * self.bias
            if total_error == 0:
                print(f"Converged at epoch {epoch+1}!")
                break

    def predict(self, x):
        weighted_sum = np.dot(x, self.weights[:2]) + self.bias * self.weights[2]
        return self.activation(weighted_sum)

# Training data for AND
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs = np.array([0, 0, 0, 1])

# Create and train the perceptron
perceptron = PerceptronAND(lr=0.1, epochs=1000)
perceptron.train(inputs, outputs)

# Test the perceptron
for x, target in zip(inputs, outputs):
    pred = perceptron.predict(x)
    print(f"Input: {x.tolist()} | Expected: {target} | Predicted: {pred}")



Converged at epoch 4!
Input: [0, 0] | Expected: 0 | Predicted: 0
Input: [0, 1] | Expected: 0 | Predicted: 0
Input: [1, 0] | Expected: 0 | Predicted: 0
Input: [1, 1] | Expected: 1 | Predicted: 1


In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[1], [0], [0], [1]])


model = Sequential([
    Dense(2, activation='relu', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=0)

preds=model.predict(X).round()

print(X, "\n")
print(y,"\n")
print(preds)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[0 0]
 [0 1]
 [1 0]
 [1 1]] 

[[1]
 [0]
 [0]
 [1]] 

[[0.]
 [1.]
 [0.]
 [1.]]
