<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/scikit_learn_scipy_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import io
import numpy as np

a='''
1.2
1.4
1.6
2.1
2.3
3
3.1
3.3
3.3
3.8
4
4.1
4.1
4.2
4.6
5
5.2
5.4
6
6.1
6.9
7.2
8
8.3
8.8
9.1
9.6
9.7
10.4
10.6
'''


b='''
39344
46206
37732
43526
39892
56643
60151
54446
64446
57190
63219
55795
56958
57082
61112
67939
66030
83089
81364
93941
91739
98274
101303
113813
109432
105583
116970
112636
122392
121873
'''


x = np.genfromtxt(io.StringIO(a), dtype=np.float32, delimiter="\n")

y = np.genfromtxt(io.StringIO(b), dtype=int)

We have 30 independent variables x and 30 dependent variables y

In [ ]:
# print side-by-side t0 make easier to see
np.set_printoptions(suppress=True)

print ("\t x \t\t y")
np.column_stack([x,y])

	 x 		 y


array([[     1.20000005,  39344.        ],
       [     1.39999998,  46206.        ],
       [     1.60000002,  37732.        ],
       [     2.0999999 ,  43526.        ],
       [     2.29999995,  39892.        ],
       [     3.        ,  56643.        ],
       [     3.0999999 ,  60151.        ],
       [     3.29999995,  54446.        ],
       [     3.29999995,  64446.        ],
       [     3.79999995,  57190.        ],
       [     4.        ,  63219.        ],
       [     4.0999999 ,  55795.        ],
       [     4.0999999 ,  56958.        ],
       [     4.19999981,  57082.        ],
       [     4.5999999 ,  61112.        ],
       [     5.        ,  67939.        ],
       [     5.19999981,  66030.        ],
       [     5.4000001 ,  83089.        ],
       [     6.        ,  81364.        ],
       [     6.0999999 ,  93941.        ],
       [     6.9000001 ,  91739.        ],
       [     7.19999981,  98274.        ],
       [     8.        , 101303.        ],
       [   

In [ ]:
x.shape,y.shape

((30,), (30,))

# Reshape input to fit Regression API

Correct shape for regression (n_samples, n_features)

x.reshape(-1, 1) converts a 1D array of shape (n,) into a 2D array of shape (n, 1) (a column vector).

```
reshape(-1, 1)
```

**-1** means second dimension should have one colums

**1** Specifies that the second dimension (number of columns) should have exactly 1 column.


In [ ]:
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

x=x.reshape(-1,1)

print(x.shape)

y=y.reshape(-1,1)

print(y.shape)
x

(30, 1)
(30, 1)


array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]], dtype=float32)

In [ ]:
y

array([[ 39344],
       [ 46206],
       [ 37732],
       [ 43526],
       [ 39892],
       [ 56643],
       [ 60151],
       [ 54446],
       [ 64446],
       [ 57190],
       [ 63219],
       [ 55795],
       [ 56958],
       [ 57082],
       [ 61112],
       [ 67939],
       [ 66030],
       [ 83089],
       [ 81364],
       [ 93941],
       [ 91739],
       [ 98274],
       [101303],
       [113813],
       [109432],
       [105583],
       [116970],
       [112636],
       [122392],
       [121873]])

In [ ]:
reg = linear_model.LinearRegression(fit_intercept=True)

reg.fit(x,y)

print("coefficient ", reg.coef_[0])
print("intercept ", reg.intercept_)



coefficient  [9449.962]
intercept  [24848.21]


In [ ]:
preds = reg.predict(x)

np.column_stack([x,y,preds])

array([[     1.20000005,  39344.        ,  36188.1640625 ],
       [     1.39999998,  46206.        ,  38078.15625   ],
       [     1.60000002,  37732.        ,  39968.1484375 ],
       [     2.0999999 ,  43526.        ,  44693.1328125 ],
       [     2.29999995,  39892.        ,  46583.125     ],
       [     3.        ,  56643.        ,  53198.09765625],
       [     3.0999999 ,  60151.        ,  54143.09375   ],
       [     3.29999995,  54446.        ,  56033.0859375 ],
       [     3.29999995,  64446.        ,  56033.0859375 ],
       [     3.79999995,  57190.        ,  60758.06640625],
       [     4.        ,  63219.        ,  62648.05859375],
       [     4.0999999 ,  55795.        ,  63593.0546875 ],
       [     4.0999999 ,  56958.        ,  63593.0546875 ],
       [     4.19999981,  57082.        ,  64538.05078125],
       [     4.5999999 ,  61112.        ,  68318.03125   ],
       [     5.        ,  67939.        ,  72098.015625  ],
       [     5.19999981,  66030.        

## R-squared score (R²)
also called the **coefficient of determination**, explains the variance in the dependent (target) variable. It provides insight into the goodness-of-fit of the model.

*	R² = 1 : The model perfectly predicts the target variable, meaning all data points lie exactly on the regression line.

*	R² = 0: The model explains none of the variance in the target variable; it performs no better than simply predicting the mean of the target variable.

*	R² < 0: The model performs worse than predicting the mean, indicating a poor fit.

## Mean Square Error**

$\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$

* $\hat{y}_i$ : prediction
* $y_i$ : observation



In [ ]:

mse = mean_squared_error(y, preds)

r2 = r2_score(y, preds)

# Print metrics
print(f"Mean Squared Error (MSE): {mse:.4f}")

print(f"R-squared (R²): {r2:.4f}")

Mean Squared Error (MSE): 31270950.0000
R-squared (R²): 0.9570


#Use Scipy


The shape of X should be `(n_samples, n_features)`, where:

* **n_samples** is the number of data points (30 in this case).
* **n_features** is the number of features (2: the intercept term and the independent variable `x`).


```

X = np.vstack([np.ones_like(x), x]).T
```


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import lstsq

x = np.genfromtxt(io.StringIO(a), dtype=np.float32, delimiter="\n")

y = np.genfromtxt(io.StringIO(b), dtype=int)

X = np.vstack([np.ones_like(x), x])

print("shape X", X.shape)

X

shape X (2, 30)


array([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,
         1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,
         1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
         4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
         8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6]], dtype=float32)

In [ ]:
# transpose.  swap rows for columns

X = X.T
X

array([[ 1. ,  1.2],
       [ 1. ,  1.4],
       [ 1. ,  1.6],
       [ 1. ,  2.1],
       [ 1. ,  2.3],
       [ 1. ,  3. ],
       [ 1. ,  3.1],
       [ 1. ,  3.3],
       [ 1. ,  3.3],
       [ 1. ,  3.8],
       [ 1. ,  4. ],
       [ 1. ,  4.1],
       [ 1. ,  4.1],
       [ 1. ,  4.2],
       [ 1. ,  4.6],
       [ 1. ,  5. ],
       [ 1. ,  5.2],
       [ 1. ,  5.4],
       [ 1. ,  6. ],
       [ 1. ,  6.1],
       [ 1. ,  6.9],
       [ 1. ,  7.2],
       [ 1. ,  8. ],
       [ 1. ,  8.3],
       [ 1. ,  8.8],
       [ 1. ,  9.1],
       [ 1. ,  9.6],
       [ 1. ,  9.7],
       [ 1. , 10.4],
       [ 1. , 10.6]], dtype=float32)

In [ ]:
# run linear regression

coeffs, residuals, rank, s = lstsq(X, y)



print("coefficient ", coeffs[1])
print("intercept ", coeffs[0])


coefficient  9449.962153919238
intercept  24848.20491851149




**Residuals**
So it's almost the same thing but not exactly as it does not use a single coefficient but is the absolute difference between every predicted and observated value

$\text{Residuals} = ||b - Ax||^2 = \sum_{i=1}^{m} (b_i - (Ax)_i)^2$

* $b_i$	: Observed values (target vector).
* $(Ax)_i$	: Predicted values from the least-squares solution.
* $m$	: Number of observations
* $A$ is `x`
* $x$ is `coeffs`

In [ ]:

print(f"Residuals: {residuals:,.2f}")


Residuals: 938,128,476.68
