<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/simple_linear_regression_keras_neural_networkd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Linear Regression with Keras


##Activation Function in Linear Regression for Nueral Networks

If no **activation function** is specified in a Keras `Dense` layer the layer uses the default: a linear activation, also called the identity function. This means the output of the neuron is simply the weighted sum of its inputs plus a bias, with no non-linear transformation applied.
Implications:

• The model is purely linear. With only linear activations (or no activation), the network is mathematically equivalent to a linear regression model, regardless of how many layers you stack.

• The model cannot learn or represent any non-linear relationships in your data. All it can do is fit a straight line (or a hyperplane in higher dimensions) to your data.

• If you add more layers, they collapse into a single linear transformation, so the “depth” of the network is meaningless without non-linear activations.

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.optimizers import SGD
import numpy as np

# Data generation
x = np.arange(12).reshape(-1, 1)
y = 3 * x

# Normalization
scaler_x = MinMaxScaler()
x_scaled = scaler_x.fit_transform(x)

scaler_y = MinMaxScaler()
y_scaled = scaler_y.fit_transform(y)

# Model setup
#  # Single neuron with input dimension of 1
model = Sequential()
model.add(Dense(1))
model.compile(optimizer=SGD(learning_rate=0.01), loss='mse')

# Training
history = model.fit(x_scaled, y_scaled, epochs=1000, verbose=0)

# Predictions (with inverse scaling)
predictions_scaled = model.predict(x_scaled)
predictions = scaler_y.inverse_transform(predictions_scaled)

# Results
print("\nOriginal vs Predicted:")
print(np.column_stack([x, y, predictions]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

Original vs Predicted:
[[ 0.          0.          4.07099056]
 [ 1.          3.          6.38816357]
 [ 2.          6.          8.70533752]
 [ 3.          9.         11.02251148]
 [ 4.         12.         13.33968449]
 [ 5.         15.         15.65685749]
 [ 6.         18.         17.97403145]
 [ 7.         21.         20.29120445]
 [ 8.         24.         22.60837746]
 [ 9.         27.         24.92555046]
 [10.         30.         27.24272346]
 [11.         33.         29.55989647]]
