<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/ml/simple_linear_regression_keras_neural_networkd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Linear Regression with Keras


##Activation Function in Linear Regression for Nueral Networks

If no **activation function** is specified in a Keras `Dense` layer the layer uses the default: a linear activation, also called the identity function. This means the output of the neuron is simply the weighted sum of its inputs plus a bias, with no non-linear transformation applied.
Implications:

• The model is purely linear. With only linear activations (or no activation), the network is mathematically equivalent to a linear regression model, regardless of how many layers you stack.

• The model cannot learn or represent any non-linear relationships in your data. All it can do is fit a straight line (or a hyperplane in higher dimensions) to your data.

• If you add more layers, they collapse into a single linear transformation, so the “depth” of the network is meaningless without non-linear activations.

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.optimizers import SGD
import numpy as np
np.set_printoptions(suppress=True)

# Data generation
x = np.arange(12).reshape(-1, 1)
y = 3 * x

# don't use scaler with small amount of data and linear model
# it's overkill and not likely to work

# Model setup
#  # Single neuron with input dimension of 1
model = Sequential()
model.add(Dense(1))
model.compile(optimizer=SGD(learning_rate=0.01), loss='mse')

# Training
history = model.fit(x, y, epochs=500, verbose=0)

# Predictions (with inverse scaling)
predictions = model.predict(x)


# Results
print("\nOriginal vs Predicted:")
print(np.column_stack([x, y, predictions]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

Original vs Predicted:
[[ 0.          0.          0.03745208]
 [ 1.          3.          3.0325346 ]
 [ 2.          6.          6.02761745]
 [ 3.          9.          9.02269936]
 [ 4.         12.         12.01778221]
 [ 5.         15.         15.01286507]
 [ 6.         18.         18.00794792]
 [ 7.         21.         21.00303078]
 [ 8.         24.         23.99811363]
 [ 9.         27.         26.99319649]
 [10.         30.         29.98827934]
 [11.         33.         32.98336029]]
