In [2]:

import numpy as np

arr=np.array([[[1,2,3]]])
print(arr)
print(arr.shape)

[[[1 2 3]]]
(1, 1, 3)


In [6]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
arr.shape

(3, 3, 3)

In [10]:
print(np.linspace(1,10,1))
print(np.arange(11))

[1.]
[ 0  1  2  3  4  5  6  7  8  9 10]


this matrix of size 10*10*10 would have 1,0000 entries

1,1,1.......10,10,10

In [18]:
arr=np.array([[[np.ones(10),np.ones(10),np.ones(10)]]],dtype=np.int8)
print(arr)

[[[[1 1 1 1 1 1 1 1 1 1]
   [1 1 1 1 1 1 1 1 1 1]
   [1 1 1 1 1 1 1 1 1 1]]]]


fill a cube that is a 3 dimensional array of length 10


[1,0,0]
[2,0,0]
[3,0,0]
...
[10,0,0]

[1,1,0]
[1,1,1]
[1,1,2]
...
[1,1,10]

[1,1,1]
[1,2,1]
[1,3,1]
...



so this would a matrix of np.shape=(10,10,10)

we would have 1000 entries

walker says: you calculate the dot-product (cartesian product).  or there should be a function that for an vector of size 10 it creates 10 entries (we have np.arange(10)

mike say: do a for 3 nested for.  look up some kind of append function


for i in range(19):
    for j in range(10):
        for k in range(10):
            add too array [i,j,k]



and then find the line z = 1/2(x+y)

x=1
y=1

z=1


(1,1,1)
(2,2,2)


In [21]:
arr=np.array([[[np.ones(10),np.zeros(10),np.zeros(10)]]],dtype=np.int8)

print(arr)


[[[[1 1 1 1 1 1 1 1 1 1]
   [0 0 0 0 0 0 0 0 0 0]
   [0 0 0 0 0 0 0 0 0 0]]]]


In [ ]:
[1,2,3,4,5,6,7,8,9,10]