Some links:
    
    BMC Guide written by Walker
    
    https://www.bmc.com/blogs/numpy-introduction/
        
        

Numpy is for scientific computing.  It's designed to do very large matrix multplication.  And machine learning uses matrices.

[ a , b, c,
  d, e, f ]

A regular list looks like this:
    
arr=[1,2,3]    

In [12]:
import numpy as np

arr = np.array([[1],[2],[3]])
print(arr)
print(arr.shape)


[[1]
 [2]
 [3]]
(3, 1)


In [8]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [9]:
arr.shape

(3,)

In [10]:
arr = np.array([1,2,3])
print(arr)
print(arr.shape)

[1 2 3]
(3,)


In [3]:
arr.shape

(3,)

A vector is a matrix of size 5x1

[1,
2,
3,
4,
5]


A matrix has generally a size like :

[ a , b, c,
  d, e, f ]
  

In [4]:
arr=np.array([[1,2,3],[4,5,6], [7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr.shape

(3, 3)

In [13]:
y=np.array([2,3,4])
x=2*y

In [14]:
x

array([4, 6, 8])

In [15]:
print(y[0],x[0])

2 4


In [16]:
z=np.array([x,y])

In [17]:
z

array([[4, 6, 8],
       [2, 3, 4]])

In [18]:
arr=[2,3,4]
z=2*[2,3,4]

In [20]:
print([i*2 for i in arr])

[4, 6, 8]


arange as in "a" + "range" is a way to fill an array with some data


In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [23]:
arr=np.arange(10)

In [24]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
arr=np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
arr[:1]

array([[1, 2, 3]])

List all rows except the 1st one, i.e., 0

In [29]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
arr[:,1]

array([2, 5, 8])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The comma means dimension?  

In [33]:
arr[:,0]

array([1, 4, 7])

get the third row

In [34]:
arr[2,:]

array([7, 8, 9])

**Assignment** investigate  Numpy slice operations what the "," means.  And make some examples