<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/2024_02_04_numpy_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#  1 dimensional



arr=np.array([1,2,3])

arr,arr.ndim,arr.shape

(array([1, 2, 3]), 1, (3,))

In [3]:
# 2 dimensional

arr=np.array([
               [1,2,3],
               [4,5,6]
              ])

print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)

[[1 2 3]
 [4 5 6]]

ndim 2

shape (2, 3)


In [4]:
arr=np.array([
           [
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
          ],
         [
           [1, 2, 3],
           [4, 5, 6],
          [7, 8, 9]
        ],
         [
           [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]
           ]
        ])

print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)


# shape: means number of elements in each dimension

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

ndim 3

shape (3, 3, 3)


In [7]:
arr = np.random.randint(1,100,(7,7))


print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)


[[32  1 97 32 94 48 13]
 [60 65 78  3 57 60 92]
 [74 83 56 53 82 48 87]
 [43 17 53 63  9 84 58]
 [44 96 46 66 45 59 96]
 [97 45  5 37 38 10 21]
 [29 60 99 77 69 11 84]]

ndim 2

shape (7, 7)


In [10]:
arr

array([[32,  1, 97, 32, 94, 48, 13],
       [60, 65, 78,  3, 57, 60, 92],
       [74, 83, 56, 53, 82, 48, 87],
       [43, 17, 53, 63,  9, 84, 58],
       [44, 96, 46, 66, 45, 59, 96],
       [97, 45,  5, 37, 38, 10, 21],
       [29, 60, 99, 77, 69, 11, 84]])

In [ ]:

# now we show how to do slicing.  the general format for a 2x2 array is

# a[from : to -1 , from : to -1]

# the colon by itself means all elements, like a[:,:]

# so the comma seperates the axis and the colon says what to do within the axis


# first columns from the 4th and 5th rows
# remember we start counting array elements at 0 so we write 3 when we mean element 4

arr[3:5,:]

In [9]:
arr[3:5,:]

array([[43, 17, 53, 63,  9, 84, 58],
       [44, 96, 46, 66, 45, 59, 96]])

In [37]:
# here the first row is:

# [1, 2, 3, 4]

# the first column is:

# [1 , 5, 8, 13]


arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [38]:

# this would not work with a 2-dimensional python list.  why?
# but with numpy this mean print the element at row=0, column=0
arr[0,0]



1

In [39]:
# how can I print the 13?

arr[3,0]

13

In [ ]:
# arr[row from : to + 1, column from to + 1]


arr[3:5,3:5]


In [11]:
#rows,columns when it is 2 dimensional

# this means start at 0 and end and 0 because you end at 1 before the last number

arr[0:1,:]

array([[32,  1, 97, 32, 94, 48, 13]])

In [12]:
arr[:,0:1]

array([[32],
       [60],
       [74],
       [43],
       [44],
       [97],
       [29]])

In [13]:
arr[:,0:1].ndim,arr[:,0:1].shape

(2, (7, 1))

In [17]:
# print first two columns

# array[from row : to row + 1 , from column to column + 1]

# you should not use reserve works like array for variable names


arr[0:2,:]

array([[32,  1, 97, 32, 94, 48, 13],
       [60, 65, 78,  3, 57, 60, 92]])

In [23]:

# make 16 elements ranging from 1 to 16

arr=np.linspace(1,16,16)

# this would be the same as writing

arr=np.linspace(1,16,16,(16,),dtype=np.int16)

print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

ndim 1

shape (16,)


In [24]:



# here we show how to print every other element.

# so the format is [from : to : step]

b=arr[0:4:2]

print(b)
print("\nndim", b.ndim)
print("\nshape",b.shape)

[1 3]

ndim 1

shape (2,)


In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int16)

In [26]:
# start

# this is invalid

#a[start=0,stop=4,step=2]

# function(arg1=a, arg2=b)

# address operators a[0]

a[0:4:2]

array([1, 3], dtype=int16)

In [31]:
a[0:4]

array([1, 2, 3, 4], dtype=int16)

In [32]:
d=[[1,2,3],
   [4,5,6]]


# addressing things in a list is simpler

d[0][0]



1

In [ ]:
# original rule

# a[from : to -1 , from : to -1]

# that is quite different from

# why is there no comma?  because it's one dimensional

a[0:4]




In [36]:
####. Wait for next class to do this


# here we show that y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d]

# first let's make the array have 2 dimensions using reshape.  we have 16 elements
# which w can divide into 4 rows and 4 columns


# you can designate the type of number when you create is using dtype
# but you can cast the type use astype

# I can cast a float to an integer, but will I lose the decimal point?  or does it round

# I can cast an integer to a float like take 1 and make 1.0.  or 1.  that's obviously legal

a=arr.reshape(4,4).astype(np.int8)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [ ]:
 #here we show that y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d]


# lets print the 2nd and 3rd row item from the 2rd and 3rd column

a[1:3, 1:3]


# Homework

1. (difficult) For the 4 x 4 array, how can you print elements along the diagonal

2.  easy.  create an array of numbers from 1 to 25 with shape (25,)

3. create an array of numbers from 1 to 25 with shape (5,5)

4.  create an array of 20 random integers ranging from 10 to 40

5.  reshapse item (4) to be (4,5)


