<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/2026_02_04_numpy_slicing_diagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# now we show how to do slicing.  the general format for a 2x2 array is

# a[from : to -1 , from : to -1]

# the colon by itself means all elements, like a[:,:]

# so the comma seperates the axis and the colon says what to do within the axis


# first columns from the 4th and 5th rows
# remember we start counting array elements at 0 so we write 3 when we mean element 4

arr[3:5,:]

array([[ 1, 79, 46,  4, 41, 48, 91],
       [67, 11, 35, 57, 64,  2, 41]])

In [ ]:
arr[3:5,:]

array([[ 1, 79, 46,  4, 41, 48, 91],
       [67, 11, 35, 57, 64,  2, 41]])

In [ ]:
# here the first row is:

# [1, 2, 3, 4]

# the first column is:

# [1 , 5, 8, 13]


arr

array([[80, 12, 26, 76, 30, 12, 57],
       [37, 93, 76, 28, 64, 47, 84],
       [91, 37, 25, 85,  4, 82, 17],
       [ 1, 79, 46,  4, 41, 48, 91],
       [67, 11, 35, 57, 64,  2, 41],
       [47, 47, 37, 25, 16, 10, 22],
       [18, 16, 66, 19,  2, 34, 36]])

In [ ]:

# this would not work with a 2-dimensional python list.  why?
# but with numpy this mean print the element at row=0, column=0
arr[0,0]



80

In [ ]:
# how can I print the 13?

arr[3,0]

1

In [ ]:
# arr[row from : to + 1, column from to + 1]


arr[3:5,3:5]


array([[ 4, 41],
       [57, 64]])

In [ ]:
#rows,columns when it is 2 dimensional

# this means start at 0 and end and 0 because you end at 1 before the last number

arr[0:1,:]

array([[80, 12, 26, 76, 30, 12, 57]])

In [ ]:
arr[:,0:1]

array([[80],
       [37],
       [91],
       [ 1],
       [67],
       [47],
       [18]])

In [ ]:
arr[:,0:1].ndim,arr[:,0:1].shape

(2, (7, 1))

In [ ]:
# print first two columns

# array[from row : to row + 1 , from column to column + 1]

# you should not use reserve works like array for variable names


arr[0:2,:]

array([[80, 12, 26, 76, 30, 12, 57],
       [37, 93, 76, 28, 64, 47, 84]])

In [ ]:

# make 16 elements ranging from 1 to 16

arr=np.linspace(1,16,16)

# this would be the same as writing

arr=np.linspace(1,16,16,(16,),dtype=np.int16)

print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

ndim 1

shape (16,)


In [ ]:



# here we show how to print every other element.

# so the format is [from : to : step]

b=arr[0:4:2]

print(b)
print("\nndim", b.ndim)
print("\nshape",b.shape)

[1 3]

ndim 1

shape (2,)


In [ ]:
# start

# this is invalid

#a[start=0,stop=4,step=2]

# function(arg1=a, arg2=b)

# address operators a[0]

#a[0:4:2]

In [ ]:
d=[[1,2,3],
   [4,5,6]]


# addressing things in a list is simpler

d[0][0]



In [ ]:
# original rule

# a[from : to -1 , from : to -1]

# that is quite different from

# why is there no comma?  because it's one dimensional

arr[0:4]




array([1, 2, 3, 4], dtype=int16)

In [ ]:
####. Wait for next class to do this


# here we show that y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d]

# first let's make the array have 2 dimensions using reshape.  we have 16 elements
# which w can divide into 4 rows and 4 columns


# you can designate the type of number when you create is using dtype
# but you can cast the type use astype

# I can cast a float to an integer, but will I lose the decimal point?  or does it round

# I can cast an integer to a float like take 1 and make 1.0.  or 1.  that's obviously legal

a=arr.reshape(4,4).astype(np.int8)
a

In [ ]:
 #here we show that y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d]


# lets print the 2nd and 3rd row item from the 2rd and 3rd column

a[1:3, 1:3]


# Homework

1. (difficult) For the 4 x 4 array, how can you print elements along the diagonal

2.  easy.  create an array of numbers from 1 to 25 with shape (25,)

3. create an array of numbers from 1 to 25 with shape (5,5)

4.  create an array of 20 random integers ranging from 10 to 40

5.  reshapse item (4) to be (4,5)




In [ ]:
# print items along diagonal

a=arr.reshape(4,4)
print(a, "\n")

# first it would need to have a diagonal

# in other words it would need to have a line where row number = column number and go all the way from one corner to another

a[:,2]


# we want

# 1, 6, 11, 16





[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 



array([ 3,  7, 11, 15], dtype=int16)

so we want:

```
[[a[0,0],a[1,1],a[2,2],a[3,3]]
```

In [ ]:
#hard code diagonal

[a[0,0],a[1,1],a[2,2],a[3,3]]

[1, 6, 11, 16]

In [ ]:
# cheat and reshape and step through it

b=a.reshape(16,)
print(a, "\n")

print("b", b)

print("diagonal", b[0:16:5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

b [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
diagonal [ 1  6 11 16]


In [ ]:
a[np.arange(a.shape[0]), np.arange(a.shape[1])]

array([ 1,  6, 11, 16], dtype=int16)

In [ ]:
a.shape

(4, 4)

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
a[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16], dtype=int16)