<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/calculate_linear_regression_manually.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Algorithm for Least Squares with Zero Intercept

1. **Initialize the Coefficient**:
   - Start with a guess for the slope ($ b $).
   - For example, $ b = 1 $.

2. **Compute Predictions**:
   - Use the current slope ($ b $) to predict $ \hat{y}_i = b \cdot x_i $.

3. **Calculate Error**:
   - Compute the Sum of Squared Errors (SSE):
$$
\text{SSE} = \sum_{i=1}^n (y_i - \hat{y}_i)^2 = \sum_{i=1}^n (y_i - b \cdot x_i)^2
$$


4. **Adjust Coefficient**:
   - If SSE decreases, increase $ b $ slightly.
   - If SSE increases, decrease $ b $ slightly.
   - Use a small step size ($ \Delta b $) for adjustments.

5. **Repeat Until Convergence**:
   - Stop when SSE stabilizes or changes by less than a small threshold (e.g., $ 0.001 $).




In [ ]:
x = np.array([0, 1, 2])

# guess the coefficient, let b = 1
# calculate y =  b * x

# calculate math.sqrt((y - b * x) ** 2 )

math.sqrt( )


#  setup

write an algorithm to find the lowest mean squared error

```
n , n + 1, n + 2



Σ i=0 to 2 of n + i

i = 0,  n + i = n + 0 = n
i = 1, n + i, n + 1
i = 2, n + i, n + 2
```

for i in len(array):
  do something

In [25]:
# make up some linear function just a any m


import numpy as np


# m is actual correct answer.  it is the coefficient

# the goal is to an algorithm to find  m
m = 2


x = np.array([0,1,2,3,4,6,7,8,9])
y = m * x
y

array([ 0,  2,  4,  6,  8, 12, 14, 16, 18])

In [26]:
x


array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [27]:
y

array([ 0,  2,  4,  6,  8, 12, 14, 16, 18])

In [28]:
# let b = 3

b = 3

ŷ = b * x

# here is the first guess
ŷ

array([ 0,  3,  6,  9, 12, 18, 21, 24, 27])

In [3]:
# solve for minimum error.
# guess slop m
# intercept is 0

m=3

lr = 0.1
converged = 0.01

# calculate error

# y = 3 * x + 0

ŷ  = 3 * x
print("ŷ ", y)

# calculate errors

# calculate mean (average error)



array([ 0,  3,  6,  9, 12, 18, 21, 24, 27])

In [ ]:
# what I need to do is first the error for each element in y, ŷ

In [29]:
y - ŷ

array([ 0, -1, -2, -3, -4, -6, -7, -8, -9])

In [33]:

import math

def mse(x,y):
    return math.sqrt((x - y)**2)


In [34]:
mse(0,0)

0.0

In [35]:
mse(1,2)

1.0

In [36]:
mse(4,6)

2.0

In [39]:
mse(6,9)

3.0

In [37]:
# Vectorize the function this
vectorized_function = np.vectorize(mse)

# Apply the vectorized function
result = vectorized_function(y,ŷ)


In [38]:
print(result)

d = result

[0. 1. 2. 3. 4. 6. 7. 8. 9.]


In [40]:
# this shows y = m * x

# is our first guess (b we guessed to be 3) ŷ = 3 * x

# d is our mse math.sqrt((ŷ - y)**2)




np.column_stack([y, ŷ, d])

array([[ 0.,  0.,  0.],
       [ 2.,  3.,  1.],
       [ 4.,  6.,  2.],
       [ 6.,  9.,  3.],
       [ 8., 12.,  4.],
       [12., 18.,  6.],
       [14., 21.,  7.],
       [16., 24.,  8.],
       [18., 27.,  9.]])

In [68]:
# our mean square error

mse_quess = np.mean(d)

print("first guess mse_quess", mse_quess)


# the agorithm is done when mse_quess - m = 0.01

# for example we could stop when we mse_quess 2.01



first guess mse_quess 4.444444444444445


In [56]:
# adjust m (the guess) by some small value (learning rate)

lr = 0.1

new_m = m + lr

# calulate ŷ again



# check the error


# compute new error to old error

# if the error increase then our guess it too high, to take new_m_second_time m - lr



# keep going until this

# in a perfect work eventually the difference between the calculation (predictions) and observations would be 0

# looking for the minium error so when ŷ - y = 0.1 stop



print("original guess was b=", b)

print("first guess array was ŷ ", ŷ)

print("and the correct answer was y ", y)

original guess was b= 3
first guess array was ŷ  [ 0  3  6  9 12 18 21 24 27]
and the correct answer was y  [ 0  2  4  6  8 12 14 16 18]


In [59]:
# second iteration

lr = 0.1

new_m = b + lr

print("our second quess was afer adding the learning rate new_m=", new_m)

ŷ_new = new_m * x

ŷ_new


#mse_quess

our second quess was afer adding the learning rate new_m= 3.1


array([ 0. ,  3.1,  6.2,  9.3, 12.4, 18.6, 21.7, 24.8, 27.9])

In [60]:
error_new = vectorized_function(y,ŷ_new)
error_new

print("this is our second guess")

this is our second guess


In [61]:
np.column_stack([y, ŷ_new, error_new])

array([[ 0. ,  0. ,  0. ],
       [ 2. ,  3.1,  1.1],
       [ 4. ,  6.2,  2.2],
       [ 6. ,  9.3,  3.3],
       [ 8. , 12.4,  4.4],
       [12. , 18.6,  6.6],
       [14. , 21.7,  7.7],
       [16. , 24.8,  8.8],
       [18. , 27.9,  9.9]])

In [62]:
mse_quess_new = np.mean(error_new)

In [71]:
print("first guess mse_guess", mse_quess)


print("second guess mse_guess_new", mse_quess_new)

print(" difference between subsequent guesses mse_quess-mse_quess_new",  mse_quess-mse_quess_new)



first guess mse_guess 4.444444444444445
second guess mse_guess_new 4.888888888888889
 difference between subsequent guesses mse_quess-mse_quess_new -0.44444444444444464


In [ ]:
# now we need to calculate the next guess

# we have to figure out whether to add or subtract the lr to get the next guess


# the different now is


# open question is the new_new_guess doe it need to go up or down


