<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/Copy_of_2026_02_04_numpy_slicing_diagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

# now we show how to do slicing.  the general format for a 2x2 array is

# a[from : to -1 , from : to -1]

# the colon by itself means all elements, like a[:,:]

# so the comma seperates the axis and the colon says what to do within the axis


# first columns from the 4th and 5th rows
# remember we start counting array elements at 0 so we write 3 when we mean element 4

arr=np.random.randint(1,100,(10,10))

arr


array([[99, 70, 67, 64, 26, 86, 73, 97, 63, 45],
       [64, 79, 97, 68, 70, 64,  3, 55, 98, 93],
       [ 2, 93, 80, 70, 65, 40, 14, 11, 64, 29],
       [64, 67, 35, 24, 94, 36, 31, 88,  8, 91],
       [76, 20,  5, 15, 74, 10, 71, 27, 49, 36],
       [99, 53, 12, 88, 41, 94, 97, 62, 28, 54],
       [51, 68,  1, 23, 91, 82, 50, 33, 67, 78],
       [36, 45, 98, 67, 58, 82, 75,  2, 12,  2],
       [92,  3, 89,  5, 70, 28, 55, 65, 72, 98],
       [99, 51, 54, 97, 54, 77, 64, 63, 34, 57]])

In [ ]:
arr[3:5,:]

array([[64, 67, 35, 24, 94, 36, 31, 88,  8, 91],
       [76, 20,  5, 15, 74, 10, 71, 27, 49, 36]])

In [ ]:
# arr[rows, columns]

# arrr[start:stop -1, start-stop - 1]

arr[3:5,0:2]

array([[64, 67],
       [76, 20]])

In [ ]:
arr=np.random.randint(1,100,(2,5,10))

In [ ]:
arr

array([[[83, 63, 76, 76, 38, 69, 92, 81, 32, 89],
        [52, 92, 38,  9, 47, 87, 92, 30, 44, 77],
        [95,  3, 55, 95, 26, 24, 49, 99, 14, 26],
        [57,  2, 39, 11, 51, 93, 66, 21, 24, 75],
        [91, 12, 73,  2,  2, 80, 59,  9, 32, 21]],

       [[ 3,  7, 96, 28, 96, 46, 69, 50, 29, 89],
        [77,  2, 17, 31, 89, 58, 77, 19, 75, 65],
        [31, 45, 58, 61, 86, 89, 75, 81, 68, 13],
        [79,  5, 64, 64, 18, 40, 25, 34, 58, 74],
        [37, 74, 20, 88, 22, 47, 94, 40, 58, 63]]])

In [ ]:
# get the first two dimensional array

arr[0,:,:]

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89],
       [52, 92, 38,  9, 47, 87, 92, 30, 44, 77],
       [95,  3, 55, 95, 26, 24, 49, 99, 14, 26],
       [57,  2, 39, 11, 51, 93, 66, 21, 24, 75],
       [91, 12, 73,  2,  2, 80, 59,  9, 32, 21]])

In [ ]:
# get first two rows out of first 2 dimensional array in this 3 dimensional object

b=arr[0,0:2,:]
b

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89],
       [52, 92, 38,  9, 47, 87, 92, 30, 44, 77]])

In [ ]:
b.shape

(2, 10)

In [ ]:
b.reshape(1,20)

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89, 52, 92, 38,  9, 47, 87,
        92, 30, 44, 77]])

In [ ]:
b.reshape(1,-1)

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89, 52, 92, 38,  9, 47, 87,
        92, 30, 44, 77]])

In [ ]:
b.reshape(5,-1)

array([[83, 63, 76, 76],
       [38, 69, 92, 81],
       [32, 89, 52, 92],
       [38,  9, 47, 87],
       [92, 30, 44, 77]])

# Homework

1. (difficult) create a  4 x 4 array, how can you print elements along the diagonal.  write a for-loop

2.  easy.  create an array of numbers from 1 to 25 with shape (25,)

3. create an array of numbers from 1 to 25 with shape (5,5)

4.  create an array of 20 random integers ranging from 10 to 40 with shape (3,4)

5.  reshapse item (4) to be (4,5)

6.  give 2 examples of reshape






In [ ]:
arr=np.random.randint(1,100,(4,4))

arr

array([[74, 20, 35, 44],
       [77, 93, 67, 69],
       [14, 73, 25, 46],
       [11, 25, 97, 81]])

In [ ]:
arr[2,2]

np.int64(25)

In [ ]:
arr[1,1]

np.int64(93)

In [ ]:
#hard code diagonal

# diagonal are elements such that row_number = col_number



[a[0,0],a[1,1],a[2,2],a[3,3]]