<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/10_july_2023_numpy_matrices_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

a = np.array([[2 , -2], [5, 3]] )
b = np.array([[-1 , 4], [7, -6]] )

np.dot(a,b)

array([[-16,  20],
       [ 16,   2]])

In [6]:
np.matmul(a,b)

array([[-16,  20],
       [ 16,   2]])

In [8]:
v1 = np.array([1,2])
v2 = np.array([3,
               4])

1*3+2*4

np.dot(v1,v2)

11

In [15]:
a = np.arange(12)**2  # the first 12 square numbers
print("a", a)

i = np.array([1, 1, 3, 8, 5, 2])  # an array of indices

print("\na[i]", a[i])  # the elements of `a` at the positions `i`


j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
print("\na[j]",a[j])  # the same shape as `j`


a [  0   1   4   9  16  25  36  49  64  81 100 121]

a[i] [ 1  1  9 64 25  4]

a[j] [[ 9 16]
 [81 49]]


In [17]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 0],  # each value corresponds to a color in the palette
                  [0, 3, 4, 0]])
palette[image]  # the (2, 4, 3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [26]:
image

array([[0, 1, 2, 0],
       [0, 3, 4, 0]])

In [24]:
palette.shape
np.array([ 0,   0,   0]).shape

(3,)