<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/2023_03_8_3D_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

x = np.array([
     [1,2, 3],
    [4, 5 , 6],
     [7, 8, 9]
    ]
     )

y = np.array([
     [1,2, 3],
      [4, 5 , 6],
     [7, 8, 9]
    ]
     )

z = np.array([
     [1,2, 3],
      [4, 5 , 6],
     [7, 8, 9]
    ]
     )



d3 = np.array([x,y,z])
print(d3)
print("\nd3 shape", d3.shape)
print("\nd3 dim ", d3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

d3 shape (3, 3, 3)

d3 dim  3
