<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/2023_03_15_more_slicing_lecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import numpy as np

array = np.random.randint(1,100,(7,7))
print(array)

print("\n")

# select 3rd and 4th rows all columns
# select 3rd and 4th columns all rows

# array[start at: end at 1 less than]

print(array[3:5,:])

print("\n")

print(array[:,3:5])




[[12 94 11 63  5 26 79]
 [37 30 48 95 22  1 43]
 [84 17 91 89 16 54 99]
 [44 82 76 64 47 32 17]
 [59 53 40  6 88 71 70]
 [68 66 73 75 17 64 29]
 [44 46 35 65  4 14 77]]


[[44 82 76 64 47 32 17]
 [59 53 40  6 88 71 70]]


[[63  5]
 [95 22]
 [89 16]
 [64 47]
 [ 6 88]
 [75 17]
 [65  4]]


In [4]:
#. first index is row array[1st is row, the 2nd is column]

# array[0:3 means print from 0 to 2 index number]

array[0:3,0:4]


array([[12, 94, 11, 63],
       [37, 30, 48, 95],
       [84, 17, 91, 89]])

In [7]:
a=np.linspace(1,16,16).astype(np.int8)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int8)

In [10]:
# ndim means dimenion

print(a.ndim)

# shape means number of elements along each dimension

print(a.shape)

1
(16,)


In [12]:
np.array([1,2,3,4,5,6,7])

np.linspace(1,7,7)

array([1., 2., 3., 4., 5., 6., 7.])

In [15]:
a=a.reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [16]:
print(a[0:4,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [17]:
print(a[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
# a[from, to - 1, step]


a[0:4:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]], dtype=int8)

In [19]:

f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int8)

[ 1  7 13 19 25]
[ 1  5  9 13 17 21 25]
[ 1  6 11 16 21]


In [32]:
# y[a:b,c:d] is the same as
# y[a:b,:][:,c:d] or y[a:b][:,c:d]

print(a[1:3, 1:3])
print("\n")


# this is easy to see if you think of this as two slices

# step 1:  go get rows 1 and 2 and all columns

# step 2: from what you created above go yet all rows and columns 1 and 2

print(a[1:3,:][:,1:3])



[[ 6  7]
 [10 11]]


[[ 6  7]
 [10 11]]


In [34]:

a[1:3,:][:,1:3]


array([[ 6,  7],
       [10, 11]], dtype=int8)

In [36]:
# short-hand notation.  shorthand means a different way to write something

# Diana.  Lady "Di"



# a[0:5] is the same as a[*5]

print(a[0:4])

print("\n")

print(a[:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [37]:
b = np.array([10, 20, 30, 40, 50, 60, 70, 80])


# this means start from the end and go backways


b[-4]


50

```

def f(x)
   return x

for i in [1,2,3,4,5]:
   print(i)


[[1,2,3],
 [4,5,6],
 [7,8,9]]

```


In [38]:
d=np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])

d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# in a 2 array a diagonal are the elements where the row number and the column number are the same

print(d[0,0])
print(d[1,1])
print(d[2,2])

1
5
9


In [42]:
# this is the number of elements along the first dimension

d.shape[0]

3

```
Homework:

write an algorithm to do that:

make a loop to loop 3 times, d.shape[0]

print the element at (i,i)

remember we use i in loops as in


for i in [1,2,3]:
   print(i)


don't hard-codem use d.shape[0]


first get it working to just print the elements

makeing the function will be a little harder because  you have to return the array:  [1, 5, 9]

that requires creating and empty array the add one element to it three times and then returning that

if you can figure this out then do it: make it a function


def diagonal():

    # return the elements along the diagonal





```


```

```

# Homework extra credit : difficult

# why does the last print not print the last element

# print every 5th element
f=np.linspace(1,25,25).astype(np.int8)

print(f[0:25:6])
print(f[0:25:4])
print(f[0:25:5])

```