<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/2024_03_05_numpy_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])


In [22]:
# nvidia

# GPUs graphical processing unit

# Microsoft put billions of dollars into chatgpt

# they spent the money on GPUs

# because machine learning is mainly matrix multiplicate

# as you do this asynchronously




In [23]:
# ndim(x)

# dimensions and axes are the same



np.linalg.matrix_rank(x)

1

In [24]:
# this shows that axes and dimensions are not the same

# since this is 1


np.linalg.matrix_rank(np.array([
                  [1.0, 2.0, 3.0, 4.0, 5.0]
                  ]))



1

In [25]:
np.array([
                  [1.0, 2.0, 3.0, 4.0, 5.0]
                  ]).ndim

2

In [26]:
np.array([[[1], [2], [3], [4], [5]]]).ndim

3

In [27]:
# this is a 2 dimensional function

#y=f(x)

# a line is a 1 dimensional


# <--------------0------------->

# in a two dimensional coordinate system we write x,y pairs like this

#(2,3)

#(x=2,y=3)

# in a 3 dimensional coordinate system we have three dimension

# some point (x=0,y=0,z=0)








In [28]:
twoD=np.array([[1], [2], [3], [4], [5]])
twoD


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
y=np.array([
 [1,1],
 [2,2],
 [3,3]
])

y.ndim
y

array([[1, 1],
       [2, 2],
       [3, 3]])

In [30]:
y=np.array([
 [1,1,1],
 [2,2,2],
 [3,3,3]
])

y.ndim


2

In [31]:
# first row

# here 0 means first dimension go get 0
# here : second dimenion go get everything on that dimension

# this is called a slicing operation

y[0,:]

array([1, 1, 1])

In [32]:
# first colum

y[:,0]

array([1, 2, 3])

In [33]:
y[:,:]

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
** definitions**

#shape-the number of elements along each dimension of the array
#dimension-the same as axes
#rank-the number of dimensions


In [35]:
y=np.array([
 [1,1,1],
 [2,2,2],
 [3,3,3]
])

print("dim",y.ndim)
print("shape", y.shape)


dim 2
shape (3, 3)


In [36]:
y = np.array([1, 2, 3, 4, 5])

print("dim",y.ndim)
print("shape", y.shape)

dim 1
shape (5,)


In [37]:
y = np.array([[1, 2, 3, 4, 5]])

print("dim",y.ndim)
print("shape", y.shape)

# so given the definition of shape it must be that we have 1 element
# on the first dimension and 5 along the second dimension

dim 2
shape (1, 5)


In NumPy, the .shape attribute of an array is a tuple that contains the size of the array along each of its dimensions. The length of the shape tuple is therefore the number of dimensions, ndim.

For a 2D array (a matrix), the shape would be (m, n), where m is the number of rows and n is the number of columns.

In [38]:
y = np.array([[1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5]])

print("dim",y.ndim)
print("shape", y.shape)

dim 2
shape (2, 5)


# homework

1.  create a 2 dimensional array.  print its shape and dimensions
2. create a 3 dimensional array.  print its shape and dimensions
3. create a 4 dimensional array.  print its shape and dimensions.  hint: to add a dimension just add another pair of brackets [].  so a 4 dimensional array will have [[[[...]]]]





