<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/2024_02_06_normal_distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The google spreadsheet that goes with this Python is [here](https://docs.google.com/spreadsheets/d/1eNj096W3kvPCkLuU3MSGkTD4LsXyZ3gxlJwZthYMh9M/edit?usp=sharing

In [3]:
import numpy as np

fiveRandomNumbers=np.random.randint(1, 7, 300)

In [4]:
fiveRandomNumbers

array([1, 4, 2, 5, 4, 5, 4, 2, 4, 5, 4, 2, 3, 3, 2, 6, 1, 5, 5, 4, 3, 5,
       1, 3, 5, 4, 5, 5, 5, 4, 4, 3, 5, 6, 4, 3, 2, 4, 2, 3, 5, 1, 3, 5,
       6, 6, 1, 5, 3, 5, 5, 1, 3, 2, 4, 5, 5, 2, 1, 4, 4, 1, 5, 3, 3, 2,
       1, 5, 1, 5, 3, 6, 5, 3, 2, 1, 3, 1, 5, 1, 1, 5, 4, 5, 2, 1, 6, 4,
       3, 6, 2, 1, 4, 3, 5, 5, 5, 2, 3, 4, 4, 2, 5, 5, 1, 6, 5, 1, 3, 6,
       4, 5, 3, 2, 6, 5, 6, 1, 3, 5, 1, 5, 1, 6, 1, 3, 1, 2, 4, 1, 6, 2,
       3, 3, 3, 5, 3, 5, 2, 6, 3, 5, 3, 4, 6, 5, 3, 2, 6, 3, 6, 6, 4, 2,
       3, 2, 2, 1, 3, 1, 2, 3, 2, 3, 1, 2, 1, 6, 2, 2, 6, 5, 5, 1, 4, 5,
       5, 5, 2, 4, 4, 6, 3, 5, 1, 5, 1, 4, 4, 5, 3, 2, 4, 2, 1, 1, 1, 2,
       4, 3, 1, 4, 2, 3, 2, 6, 3, 3, 1, 2, 3, 1, 3, 1, 2, 5, 4, 5, 3, 3,
       3, 1, 6, 3, 1, 5, 6, 1, 1, 1, 3, 2, 6, 2, 4, 3, 1, 5, 1, 3, 5, 6,
       3, 5, 3, 5, 4, 5, 5, 1, 1, 6, 6, 5, 5, 2, 1, 6, 1, 3, 5, 4, 5, 6,
       1, 3, 3, 3, 5, 6, 5, 6, 1, 6, 2, 1, 4, 5, 4, 3, 4, 6, 4, 2, 1, 1,
       3, 5, 3, 5, 6, 3, 4, 1, 5, 1, 6, 2, 6, 1])

In [17]:
diceRollCount=np.histogram(fiveRandomNumbers,bins=[1,2,3,4,5,6,7])


In [16]:
diceRollCount

(array([57,  0, 41,  0, 59,  0, 40,  0, 66, 37]),
 array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ]))

In [14]:
#how do we calculate random integers using numpy using a normal distribution



# homework will be change the numbers that we calculated in the normal
# distribution to integers




# calculate a histogram

# Generate 10 random integers from a normal distribution with mean 50 and standard deviation 10

mean = 10
std_dev = 3
random_integers_normal = np.random.normal(mean, std_dev, size=30)
print("Random integers from normal distribution:", random_integers_normal)

# so look up using google how to convert the numbers in the numpy array random_integers_normal to integers

# then calculat the histogram like I did above.  in orders put:

np.histogram(random_integers_normal,bins=[1,2,3,4,5,6,7 (put 1 to 31 here)])

Random integers from normal distribution: [ 9.95015142 12.13796488 11.25159043  3.40864756 13.47232896  4.66998392
 13.14506853  9.20928997  7.21975895 14.38171668  9.56931698 14.32237782
 13.03516993  6.72737996 12.2706381   8.77596714 10.24750525  9.56336553
 14.68596356  7.93704745  7.48303934  6.63091117 10.65893596  9.3259575
  8.76179318 11.76231531  7.82831424  9.32888984  8.65957052  9.40506769]


In [18]:
# next time I will show you how to draw a chart in Python like we did in Google Sheets

In [19]:
# and this time we are hard-coding 1 to 31.  I will show you how to generate the array

In [ ]:
# 1 to 31 automatically.  hint use np.linespace()