a two dimensional array has two axis

in math this is called the cartesian plane

than is the x-y graph

In [29]:
import numpy as np

ar=np.array([1,2,3,4])
ar.shape

(4,)

In [30]:
b=ar.reshape(2,2)
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [31]:
b[0].shape

(2,)

In [32]:
[ [1,2],
   [3,4]
]

[[1, 2], [3, 4]]

In [33]:
np.array([1]).shape

(1,)

** definitions**

* shape-the number of elements along each dimension of the array
* dimension-the same as axes
* rank-the number of dimensions


In [34]:
np.linalg.matrix_rank(b)

2

In [35]:
b

array([[1, 2],
       [3, 4]])

# geometry #

in math a 2-dimensional coordinate is called the cartesian plane

why?  Because the French Rene Descartes invented it.

an element on the array is (x,y)

in a 3-dimensional coordinate system points are give at location (x,y,z)

a 1-dimensional ?  a line.  its point x


In [36]:
c=np.array([
   [[1],[2],[3]],
    [[1], [2], [3]]
])

In [37]:
np.linalg.matrix_rank(c)

array([1, 1])

In [38]:
c.shape

(2, 3, 1)

#. shape-the number of elements along each dimension of the array

since this shape has 3 numbers there must be 3 dimension

so it's saying that we have:

* 2 elements on the 1st dimension
* 3 elements on the 2nd dimension
* 1 element on the 3rd dimension


In [42]:
# this part here we have not yet covered but this is 
# slicing and operations

d = np.array([ 
              [1]
             ])
 

In [43]:
 d.shape

(1, 1)

In [ ]:
 # one dimensional
    
    [1,2]
    
# two dimensional is
   [[1,2]] 
    
# three dimensional must be:

  [[[1]]]
    

In [46]:
z=np.array(  [[[1]]])

In [48]:
z.shape

(1, 1, 1)

In [51]:
e=np.array([
    [ 
        [1]
    
    ]
    
    
])




In [52]:
e.shape

(1, 1, 1)

In [ ]:
# so it's similar to the x,y,z coordinate system

# but don't of it as math as beyond 3 dimensions you cannot
# picture that in your head

