<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/2024_02_02_histograms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


diceRolls=np.random.randint(1,7,103)

In [4]:
diceRolls

array([5, 5, 3, 4, 1, 2, 6, 1, 4, 1, 1, 2, 5, 5, 5, 5, 1, 1, 2, 6, 1, 4,
       5, 1, 5, 2, 4, 6, 2, 5, 5, 2, 5, 4, 4, 2, 5, 2, 5, 4, 1, 6, 4, 1,
       5, 4, 2, 5, 3, 5, 4, 3, 6, 2, 5, 3, 4, 3, 4, 4, 4, 1, 1, 1, 3, 3,
       2, 1, 2, 2, 6, 1, 1, 3, 1, 2, 4, 5, 3, 2, 3, 1, 1, 5, 1, 5, 2, 3,
       6, 2, 6, 3, 5, 1, 3, 6, 2, 5, 4, 6, 1, 5, 1])

In [17]:
# how many 4s did we roll?

counts = np.histogram(diceRolls,bins=[1,2,3,4,5,6,7])

In [18]:
counts

(array([23, 18, 13, 16, 23, 10]), array([1, 2, 3, 4, 5, 6, 7]))

In [11]:
rolls = np.array([1,2,2,3,4,4,4])


In [12]:
rolls

array([1, 2, 2, 3, 4, 4, 4])

In [16]:
hist=np.histogram(rolls,bins=[1,2,3,4,5])



hist

(array([1, 2, 1, 3]), array([1, 2, 3, 4, 5]))

Here is a summar of what we did.

The [google sheets is here](https://docs.google.com/spreadsheets/d/1ESpcFAKZq4Pn5M-4F1xxJ6H2M6gfcmAgMuaxcKv0tq8/edit?usp=sharing).

A histogram is a frequency count.  A normal curve is a more difficult to understand because it using real numbers.

If we do a count of dice rolling that is easy to understand.  Above we rolled one 1, two twos, etc.

We did this using the numpy histogram function


```

# here we manually put in the dice rolls.  at the top of this #notebook we used the numpy random function

rolls = np.array([1,2,2,3,4,4,4])


# here we tell it what array to count.  we have to put bins so that #it uses numbers for the edges.  otherwise we get real numbers

hist=np.histogram(rolls,bins=[1,2,3,4,5])

```


The goal of what are doing is to understand the difference between uniform (dice) and normal (student grades) distributions

