<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# matrix * multiply in place


import numpy as np

a = np.array([[2, 2, 1],
       [2, 4, 2],
       [0, 0, 0]])

b = np.array([[1],
       [2],
       [0]])


c = a * b


c

array([[2, 2, 1],
       [4, 8, 4],
       [0, 0, 0]])

In [15]:
import numpy as np

a = np.array([[2, 2, 1],
       [2, 4, 2],
       [0, 0, 0]])

b = np.array([[1, 1, 1],
       [2, 2, 2],
       [0,0,0]])


c = a * b


c

array([[2, 2, 1],
       [4, 8, 4],
       [0, 0, 0]])

In [16]:
# this is not the same as
np.dot(a,b)

array([[ 6,  6,  6],
       [10, 10, 10],
       [ 0,  0,  0]])