<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Broadcasting

Numpy explains is best in [their documentation](https://numpy.org/devdocs//user/basics.broadcasting.html)

In [ ]:



import numpy as np

a = np.array([[2, 2, 1],
       [2, 4, 2],
       [0, 0, 0]])

b = np.array([[1],
       [2],
       [0]])


c = a * b


c

array([[2, 2, 1],
       [4, 8, 4],
       [0, 0, 0]])

This is the same as

In [ ]:
import numpy as np

a = np.array([[2, 2, 1],
       [2, 4, 2],
       [0, 0, 0]])

b = np.array([[1, 1, 1],
       [2, 2, 2],
       [0,0,0]])


c = a * b


c

array([[2, 2, 1],
       [4, 8, 4],
       [0, 0, 0]])

In [ ]:
# this is not the same as
np.dot(a,b)

array([[ 6,  6,  6],
       [10, 10, 10],
       [ 0,  0,  0]])

#Broadcasting on Addition





In [4]:
import numpy as np

a=np.array([[ 1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])


b=np.array([[4],
          [3],
          [2]])

a+b


array([[ 5,  6,  7],
       [ 7,  8,  9],
       [ 9, 10, 11]])