<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra
Here we explain how to add and multiply vectors and matrices.  These operations are called **linear algebra**

> Credit.  Much of this material is adapted from Deep Learning with Python, Third Edition  François Chollet and Matthew Watson.  



## Addition

Just add each element in row, column position to the element in the same position in the second matrix.

In [51]:
import numpy as np
np.set_printoptions(suppress=True)

x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])


In [52]:


x + y

array([[ 6,  8],
       [10, 12]])

In [53]:
# Add Two Matrices times a Matrix


x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
               [7, 8]])

x + y

array([[ 6,  8],
       [10, 12]])

### Add a Vector to an Matrix

Here we have use the idea of **broadcasting**

In [54]:
 # can't add because dimensions are different
 x = np.array([[1, 2],
              [3, 4]])

 y = np.array([5, 6])

 x + y

array([[ 6,  8],
       [ 8, 10]])

In [55]:
# notice that an extra dimension is added, notice the [[]] number of brackets

y = np.expand_dims(y, axis=0)
y

array([[5, 6]])

In [56]:
# When the actual addition is done y's first row is copied to the second, i.e., broadcast

In [57]:
x + y

array([[ 6,  8],
       [ 8, 10]])

In [58]:
#It's the same as:

x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
              [5,6]])

x + y

array([[ 6,  8],
       [ 8, 10]])


# Multiplication

There are 4 cases:

1.  Scalar times a vector

2.  Vector times a vector

3.  Vector times a matrix

4.  Matrix times a matrix


### Scalar times a vector



In [59]:
x = np.array([1,2,3])

2 * x

array([2, 4, 6])

### Mutiply two Vectors

This results in a scalar, i.e., a single number

In [60]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.dot(x,y)


np.int64(32)

In [61]:
# this is the same as

1 * 4 + 2 * 5 + 3 * 6

32

### Mutiply two Arrays

You can also take the product between a matrix x and a vector y, which returns a vector where the coefficients are the products between y and the rows of x. You implement it as follows.



In [62]:
matrix = np.array([[1, 2],
                   [3, 4]])

print("matrix shape", matrix.shape)

vector = np.array([10, 20])

print("\nvector shape", vector.shape, "\n")



matrix shape (2, 2)

vector shape (2,) 



In [63]:
#the coefficients are the products between vector and the rows of matrix

np.dot(matrix,vector)



array([ 50, 110])

In [64]:
# in other words it's,

np.array([np.dot(vector, matrix[0]), np.dot(vector, matrix[1])])



array([ 50, 110])

## Multiply Two Matrices

 You can take the product of two matrices x and y if and only if x.shape[1] == y.shape[0]. The result is a matrix with shape (x.shape[0], y.shape[1]), where the coefficients are the vector products between the rows of x and the columns of y. Here’s the naive implementation:

In [65]:
x = np.array([[1,2,3],
              [3,4,5]])

y = np.array([[5,6],
              [7,8],
              [9,10]])

In [66]:
# check that number of rows in x is equal to the number of columns in y

print("shapes ", x.shape, y.shape, "\n")

assert x.shape[1] == y.shape[0]


np.dot(x,y)

shapes  (2, 3) (3, 2) 



array([[ 46,  52],
       [ 88, 100]])

In [67]:
# simpler example

x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])


print(x.shape, y.shape,"\n")

assert x.shape[1] == y.shape[0]


np.dot(x,y)

(2, 2) (2, 2) 



array([[19, 22],
       [43, 50]])

In [72]:
# the coefficients are the vector products between the rows of x and the columns of y

# rows of x: x[0], x[1]

# columns of y: y[0], y[1]

# row 1 * column 1 vector product

# Because the rows of x and the columns of y must have the same size, it follows that the width of x must match the height of y


assert x.shape[1] == y.shape[0]

# make an array of that size and initialize it to zeros

z = np.zeros((x.shape[0] , y.shape[1]))

for i in range(x.shape[0]):
      for j in range(y.shape[1]):
          row_x = x[i, :]
          column_y = y[:, j]
          z[i, j] = np.dot(row_x, column_y)

z


array([[ 30.,  70.],
       [ 70., 174.]])

More generally, you can take the product between higher-dimensional tensors, following these rules for shape compatibility:

```
(a, b, c, d) • (d,) -> (a, b, c)
(a, b, c, d) • (d, e) -> (a, b, c, e)

```

### Repeat definition from above

You can take the product of two matrices x and y if and only if x.shape[1] == y.shape[0]. The result is a matrix with shape (x.shape[0], y.shape[1]), where the coefficients are the vector products between the rows of x and the columns of y. Here’s the naive implementation.

So make a matrix where x.shape[1] = y.shape[0]

In [69]:
import numpy as np

x = np.array([[1,2,3,4],
              [5,6,7,8]])

# swap rows and columns

y = x.T

assert x.shape[1] == y.shape[0]


print(y, "\n")

np.dot(x,y)


[[1 5]
 [2 6]
 [3 7]
 [4 8]] 



array([[ 30,  70],
       [ 70, 174]])

In [71]:
# use the code we wrote above

z = np.zeros((x.shape[0] , y.shape[1]))

for i in range(x.shape[0]):
      for j in range(y.shape[1]):
          row_x = x[i, :]
          column_y = y[:, j]
          z[i, j] = np.dot(row_x, column_y)

z


array([[ 30.,  70.],
       [ 70., 174.]])