<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra
Here we explain how to add and multiply vectors and matrices.  These operations are called **linear algebra**

> Credit.  Much of this material is adapted from Deep Learning with Python, Third Edition  François Chollet and Matthew Watson.  



## Addition

Just add each element in row, column position to the element in the same position in the second matrix.

In [ ]:
import numpy as np
np.set_printoptions(suppress=True)

x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])


In [ ]:
x + y

array([[ 6,  8],
       [10, 12]])

In [ ]:
# Add Two Matrices times a Matrix


x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
               [7, 8]])

x + y

array([[ 6,  8],
       [10, 12]])

### Add a Vector to an Matrix

Here we have use the idea of **broadcasting**

In [ ]:
 # can't add because dimensions are different
 x = np.array([[1, 2],
              [3, 4]])

 y = np.array([5, 6])

 x + y

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
# notice that an extra dimension is added, notice the [[]] number of brackets

y = np.expand_dims(y, axis=0)
y

array([[5, 6]])

In [ ]:
# When the actual addition is done y's first row is copied to the second, i.e., broadcast

In [ ]:
x + y

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
#It's the same as:

x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
              [5,6]])

x + y

array([[ 6,  8],
       [ 8, 10]])


# Multiplication

There are 4 cases:

1.  Scalar times a vector

2.  Vector times a vector

3.  Vector times a matrix

4.  Matrix times a matrix


### Scalar times a vector



In [ ]:
x = np.array([1,2,3])

2 * x

array([2, 4, 6])

### Mutiply two Vectors

This results in a scalar, i.e., a single number

In [9]:
# below same as

import numpy as np

# make vertical to make easier to see as a column

x = np.array([1,
              2,
              3])

y = np.array([4,5,6])

d = 0

for i in range(x.shape[0]):
    d = d + x[i]* y[i]
d


np.int64(32)

In [5]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.dot(x,y)


np.int64(32)

In [ ]:
# this is the same as

1 * 4 + 2 * 5 + 3 * 6

32

### Mutiply two Arrays

You can also take the product between a matrix x and a vector y, which returns a vector where the coefficients are the products between y and the rows of x. You implement it as follows.



In [ ]:
matrix = np.array([[1, 2],
                   [3, 4]])

print("matrix shape", matrix.shape)

vector = np.array([10, 20])

print("\nvector shape", vector.shape, "\n")



matrix shape (2, 2)

vector shape (2,) 



In [ ]:
#the coefficients are the products between vector and the rows of matrix

np.dot(matrix,vector)



array([ 50, 110])

In [ ]:
# in other words it's,

np.array([np.dot(vector, matrix[0]), np.dot(vector, matrix[1])])



array([ 50, 110])

## Multiply Two Matrices

 You can take the product of two matrices x and y if and only if x.shape[1] == y.shape[0]. The result is a matrix with shape (x.shape[0], y.shape[1]), where the coefficients are the vector products between the rows of x and the columns of y.

 Below is the code.  Below that is a step-by-step explanation.

In [60]:
# this is just vector times vector


x = np.array([[1,2,3],
              [3,4,5]])

y = np.array([[5,6],
              [7,8],
              [9,10]])

# this is the same as rows of x times columns of y

# i.e. [1,2,3] * [5,7,9]
#      [3,4,5] * [6,8,10]

print(x[0])
print(y[:,0])

xy=np.dot(x[0],y[:,0])
print(xy)


#multiple row of each by column of second.  so obviously them just have same length

print("x.shape=", x.shape)
print("y.shape=", y.shape)

assert x.shape[1] == y.shape[0]

sum = np.zeros([x.shape[0],y.shape[1]])
print("\nmake empty array of y shape=", sum)




for i in range(x.shape[0]):
  for j in range(y.shape[1]):
    print("\ni=",i,"j=",j)
    print("row", x[i])
    print("column", y[:,j])
    #multiply the two vectors
    xy=np.dot(x[i],y[:,j])
    #add to array in correct row-column location
    sum[i,j]=xy
    print(xy)
    print("\n======next column==========")
  print("\n======next row==========")

print(sum)



[1 2 3]
[5 7 9]
46
x.shape= (2, 3)
y.shape= (3, 2)

make empty array of y shape= [[0. 0.]
 [0. 0.]]

i= 0 j= 0
row [1 2 3]
column [5 7 9]
46

======next column==========

i= 0 j= 1
row [1 2 3]
column [ 6  8 10]
52

======next column==========

======next row==========

i= 1 j= 0
row [3 4 5]
column [5 7 9]
88

======next column==========

i= 1 j= 1
row [3 4 5]
column [ 6  8 10]
100

======next column==========

======next row==========
[[ 46.  52.]
 [ 88. 100.]]


In [ ]:
x = np.array([[1,2,3],
              [3,4,5]])

y = np.array([[5,6],
              [7,8],
              [9,10]])

# check that number of rows in x is equal to the number of columns in y

print("shapes ", x.shape, y.shape, "\n")

assert x.shape[1] == y.shape[0]


np.dot(x,y)

shapes  (2, 3) (3, 2) 



array([[ 46,  52],
       [ 88, 100]])

## Step 1: Understand Matrix Dimensions
x has shape 2x3 (2 rows, 3 columns)

y has shape 3x2 (3 rows, 2 columns)

The product np.dot(x,y) will have shape (2,2) (rows of x , columns of y).

#Step 2: Compute Each Element of the Result
Each element in the resulting matrix is the dot product of a row from x and a column from y.

**First Row of Result**:
First element (46):
Row 1 of x · Column 1 of y

$$(1×5) + (2×7) + (3×9) = 5 + 14 + 27 = 46$$

**Second element (52)**:
Row 1 of x · Column 2 of y

$$(1×6) + (2×8) + (3×10) = 6 + 16 + 30 = 52$$

**Second Row of Result**:
First element (88):
Row 2 of x · Column 1 of y

$$(3×5) + (4×7) + (5×9) = 15 + 28 + 45 = 88$$

**Second element (100)**:
Row 2 of x · Column 2 of y
$$(3×6) + (4×8) + (5×10) = 18 + 32 + 50 = 100$$

##Key Rules of Matrix Multiplication
**Compatibility**:
The number of columns in the first matrix (x.shape) must equal the number of rows in the second matrix (y.shape).
Here: 3 (columns in x) = 3 (rows in y) ✔️

**Result Shape**:
The resulting matrix has dimensions (rows of x × columns of y).
Here: 2 (rows in x) × 2 (columns in y) = 2x2.

**Dot Product**:
Each element in the result is calculated by multiplying corresponding elements from a row of x and a column of y, then summing them.



In [ ]:
# simpler example

x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])


print(x.shape, y.shape,"\n")

assert x.shape[1] == y.shape[0]


np.dot(x,y)

(2, 2) (2, 2) 



array([[19, 22],
       [43, 50]])

In [ ]:
# the coefficients are the vector products between the rows of x and the columns of y

# rows of x: x[0], x[1]

# columns of y: y[0], y[1]

# row 1 * column 1 vector product

# Because the rows of x and the columns of y must have the same size, it follows that the width of x must match the height of y


assert x.shape[1] == y.shape[0]

# make an array of that size and initialize it to zeros

z = np.zeros((x.shape[0] , y.shape[1]))

for i in range(x.shape[0]):
      for j in range(y.shape[1]):
          row_x = x[i, :]
          column_y = y[:, j]
          z[i, j] = np.dot(row_x, column_y)

z


array([[19., 22.],
       [43., 50.]])

More generally, you can take the product between higher-dimensional tensors, following these rules for shape compatibility:

```
(a, b, c, d) • (d,) -> (a, b, c)
(a, b, c, d) • (d, e) -> (a, b, c, e)

```

### Repeat definition from above

You can take the product of two matrices x and y if and only if x.shape[1] == y.shape[0]. The result is a matrix with shape (x.shape[0], y.shape[1]), where the coefficients are the vector products between the rows of x and the columns of y. Here’s the naive implementation.

So make a matrix where x.shape[1] = y.shape[0]

In [ ]:
import numpy as np

x = np.array([[1,2,3,4],
              [5,6,7,8]])

# swap rows and columns

y = x.T

assert x.shape[1] == y.shape[0]


print(y, "\n")

np.dot(x,y)


[[1 5]
 [2 6]
 [3 7]
 [4 8]] 



array([[ 30,  70],
       [ 70, 174]])

In [ ]:
# explain The result is a matrix with shape (x.shape[0], y.shape[1]), where the coefficients are the vector products between the rows of x and the columns of y

# NOT READY THIS CELL

row_1_x = x[:,0]
col_1_y= y[0,:]

print(y,"\n")
print(row_1_x, "\n")
print(col_1_y)

np.dot(row_1_x, col_1_y)

[[1 5]
 [2 6]
 [3 7]
 [4 8]] 

[1 5] 

[1 5]


np.int64(26)

In [ ]:
# use the code we wrote above

z = np.zeros((x.shape[0] , y.shape[1]))

for i in range(x.shape[0]):
      for j in range(y.shape[1]):
          row_x = x[i, :]
          column_y = y[:, j]
          z[i, j] = np.dot(row_x, column_y)

z


array([[ 30.,  70.],
       [ 70., 174.]])