<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication: Dot Product

In [ ]:
# scalar times a matrix

import numpy as np

a=np.array(3)
b=np.array([
    [1,2,3],
    [4,5,6]
])

np.dot(a,b)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
# the dot product of two vectors is a scalar

a=np.array([1,2,3])
b=np.array([4,5,6])


np.dot(a,b)

np.int64(32)

In [ ]:
# same as
1*4+2*5+3*6

32

In [ ]:
a=np.array([1,2,3])

b=np.array([4,
            5,
            6])

np.dot(a,b)

np.int64(32)

In [ ]:
# multiple a vector and a matrix

a=np.array([1,2,3])

b=np.array([[4,7],
            [5,8],
            [6,9]])

np.dot(a,b)

array([32, 50])

In [ ]:
# mutiply two matrics

#The number of columns in the first matrix (a.shape) must equal the number of rows in the second matrix (b.shape)

#The resulting matrix has dimensions (rows of a , columns of b).



a=np.array([
            [1,2,3],
            [1,2,3]
            ])

b=np.array([[4,7],
            [5,8],
            [6,9]])

print("a", a, "\na.shape=", a.shape, "\na.ndim", a.ndim)
print("\nb", b, "\nb.shape=", b.shape,"\nb.ndim", b.ndim)


assert a.shape[0] == b.shape[1]

print("\nnp.dot(a,b)", np.dot(a,b))


a [[1 2 3]
 [1 2 3]] 
a.shape= (2, 3) 
a.ndim 2

b [[4 7]
 [5 8]
 [6 9]] 
b.shape= (3, 2) 
b.ndim 2

np.dot(a,b) [[32 50]
 [32 50]]


# Matrix Multiplication: matmul

| Feature                            | `np.dot`                                                | `np.matmul` (and `@` operator)                |
|-------------------------------------|--------------------------------------------------------|-----------------------------------------------|
| **1D arrays**                      | Computes vector dot product                            | Computes vector dot product                   |
| **2D arrays**                      | Matrix multiplication                                  | Matrix multiplication                         |
| **N-D arrays (N > 2)**             | Sums products over the last axis of the first array and the second-to-last axis of the second array (can lead to unintuitive results) | Performs matrix multiplication over the last two axes, broadcasting batch dimensions (more intuitive for stacks of matrices/tensors) |
| **Broadcasting (batch dimensions)**| No broadcasting for stacks of matrices                 | Yes, supports broadcasting for leading (batch) dimensions |
| **Scalar multiplication**          | Allowed                                                | Not allowed (use `*` for elementwise)         |
| **Elementwise multiplication**      | Not supported (use `np.multiply` or `*`)               | Not supported (use `np.multiply` or `*`)      |


In [ ]:


a=np.array([[1,2,3],
           [4,5,6]])

b=a

np.matmul(a,b.T)

array([[14, 32],
       [32, 77]])

# Broadcasting

**Basic Rule**:
Two dimensions are compatible when:

*They are equal, or

* One of them is 1

the smaller tensor will be broadcasted to match the shape of the larger tensor. Broadcasting consists of two steps:

1. Axes (called broadcast axes) are added to the smaller tensor to match the ndim of the larger tensor.
2. The smaller tensor is repeated alongside these new axes to match the full shape of the larger tensor.

Broadcasting allows arrays of different shapes to be used together in arithmetic operations (addition, multiplication, etc.) by automatically expanding the smaller array along dimensions of size one or missing dimensions, so their shapes become compatible

## Example np.matmul with 2D and 1D arrays

Rule for np.matmul with 2D and 1D arrays:
NumPy treats the 1D array b as a column vector (shape (3, 1)) for the operation, then removes the trailing dimension from the result.

In [ ]:
import numpy as np

a = np.array([
                      [1,1,1],
                      [2,2,2],
                      [3,3,3]
                      ])

b = np.array([4,5,6])

print("\na.shape",a.shape, "a.ndim", a.ndim)
print("\nb.shape",b.shape, "b.ndim", b.ndim)

print("\na", a)

print("\nb", b)


print("\nnp.matmul(a,b)", np.matmul(a,b))





a.shape (3, 3) a.ndim 2

b.shape (3,) b.ndim 1

a [[1 1 1]
 [2 2 2]
 [3 3 3]]

b [4 5 6]

np.matmul(a,b) [15 30 45]


#Explanation

Implicit reshaping of b for matmul:
NumPy treats b as a column vector with shape (3, 1) for the operation.

1. First row of a:

$$1*4 + 1*5 + 1*6 = 4 + 5 + 6 = 15$$


2. Second row of a:

$$2*4 + 2*5 + 2*6 = 8 + 10 + 12 = 30$$

3. Third row of a:

$$3*4 + 3*5 + 3*6 = 12 + 15 + 18 = 45$$



# The Same

This is the same as:

1. Add a dimension to b so that it goes from (3,) to (3, 1).
(This turns b into a column vector.)

2. Perform np.matmul(a, b), which multiplies each row of a by the corresponding element of b and sums the results (i.e., computes the dot product of each row of a with b).


3. Remove the singleton dimension from the result, so the output shape goes from (3, 1) to (3,).


In [ ]:
import numpy as np

a = np.array([
                      [1,1,1],
                      [2,2,2],
                      [3,3,3]
                      ])

b = np.array([
        [4],
         [5],
         [6]
        ])

print("\na.shape",a.shape, "a.ndim", a.ndim)
print("\nb.shape",b.shape, "b.ndim", b.ndim)

print("\na", a)

print("\nb", b)


# remove all dimensions of size 1

print("\nnp.matmul(a,b)", np.squeeze(np.matmul(a,b)))


a.shape (3, 3) a.ndim 2

b.shape (3, 1) b.ndim 2

a [[1 1 1]
 [2 2 2]
 [3 3 3]]

b [[4]
 [5]
 [6]]

np.matmul(a,b) [15 30 45]


# Addition



In [3]:
#Here, b is broadcast to match the shape of a (copied for each row)

import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a.ndim, b.ndim)



a + b


2 1


array([[11, 22, 33],
       [14, 25, 36]])