<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to Multiply a 3x3 Matrix by a 3x4 Matrix

### Matrix Dimensions

- **3x3 matrix**: 3 rows and 3 columns  
- **3x4 matrix**: 3 rows and 4 columns

**Matrix multiplication is possible when the number of columns in the first matrix equals the number of rows in the second matrix.**  
Here, both have 3 columns/rows, so multiplication is valid.

- **Resulting matrix:** The product will be a **3x4 matrix** (rows of the first, columns of the second).



### General Formula for the Product

$$
C = A \times B
$$

$$
C_{ij} = \sum_{k=1}^{3} a_{ik} \cdot b_{kj}
$$

Where:
- $i$ = row index (1 to 3)
- $j$ = column index (1 to 4)
- $k$ = index for summing over the shared dimension (1 to 3)

---



**In short:**  
Multiply each row of the 3x3 matrix by each column of the 3x4 matrix, sum the products, and place the result in the corresponding position of the 3x4 product matrix.


In [ ]:
import numpy as np

a = np.array([[1,2,3],
               [4,5,6],
              [7,8,9]])

b = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

assert a.shape[1] == b.shape[0]


# create an array of that size


# share Dimentions the same as the rows of the first matrix or columns on the second
sharedDim=a.shape[1]

aRows=a.shape[0]
bColumns=b.shape[1]

# create an empty array with the correct shape
c=np.zeros([a.shape[0],b.shape[1]])

for i in range(aRows):
    for j in range(bColumns):
      # make an accumulator and then plug it into the correct row, column position in c
      print("multiplying a", a[i], "and b", b[:,j])
      cSum = 0
      for k in range(sharedDim):
        cSum += a[i][k] * b[k][j]
      c[i,j]=cSum
    print("\n")

print(c)

print("\nchecking results")

np.dot(a,b)

multiplying a [1 2 3] and b [1 5 9]
multiplying a [1 2 3] and b [ 2  6 10]
multiplying a [1 2 3] and b [ 3  7 11]
multiplying a [1 2 3] and b [ 4  8 12]


multiplying a [4 5 6] and b [1 5 9]
multiplying a [4 5 6] and b [ 2  6 10]
multiplying a [4 5 6] and b [ 3  7 11]
multiplying a [4 5 6] and b [ 4  8 12]


multiplying a [7 8 9] and b [1 5 9]
multiplying a [7 8 9] and b [ 2  6 10]
multiplying a [7 8 9] and b [ 3  7 11]
multiplying a [7 8 9] and b [ 4  8 12]


[[ 38.  44.  50.  56.]
 [ 83.  98. 113. 128.]
 [128. 152. 176. 200.]]

checking results


array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])