<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to Multiply a 3x3 Matrix by a 3x4 Matrix

### Matrix Dimensions

- **3x3 matrix**: 3 rows and 3 columns  
- **3x4 matrix**: 3 rows and 4 columns

**Matrix multiplication is possible when the number of columns in the first matrix equals the number of rows in the second matrix.**  
Here, both have 3 columns/rows, so multiplication is valid.

- **Resulting matrix:** The product will be a **3x4 matrix** (rows of the first, columns of the second).

---

### Step-by-Step Process

#### 1. Define the Matrices

Let:  
- $A$ be the 3x3 matrix  
- $B$ be the 3x4 matrix

$$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14} \\
b_{21} & b_{22} & b_{23} & b_{24} \\
b_{31} & b_{32} & b_{33} & b_{34}
\end{bmatrix}
$$

---

#### 2. Compute Each Entry in the Result

The entry in row $i$, column $j$ of the result ($C_{ij}$) is calculated as:

$$
C_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + a_{i3}b_{3j}
$$

---

#### 3. Example Calculation

Suppose you want to find the entry in the **first row, second column** of the result ($C_{12}$):

$$
C_{12} = a_{11}b_{12} + a_{12}b_{22} + a_{13}b_{32}
$$

Repeat this process for all combinations of rows (1 to 3) and columns (1 to 4).

---

### General Formula for the Product

$$
C = A \times B
$$

$$
C_{ij} = \sum_{k=1}^{3} a_{ik} \cdot b_{kj}
$$

Where:
- $i$ = row index (1 to 3)
- $j$ = column index (1 to 4)
- $k$ = index for summing over the shared dimension (1 to 3)

---

### Example with Numbers

Let

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix}
$$

To find the entry in the **second row, third column** of the result ($C_{23}$):

$$
C_{23} = 4 \times 3 + 5 \times 7 + 6 \times 11 = 12 + 35 + 66 = 113
$$

---

### Resulting Matrix Structure

$$
C = \begin{bmatrix}
C_{11} & C_{12} & C_{13} & C_{14} \\
C_{21} & C_{22} & C_{23} & C_{24} \\
C_{31} & C_{32} & C_{33} & C_{34}
\end{bmatrix}
$$

---

### Summary Table

| Step                | What to Do                                                                 |
|---------------------|----------------------------------------------------------------------------|
| 1. Check dimensions | Columns of first = rows of second (both 3)                                 |
| 2. Set up result    | Result is 3x4 matrix                                                       |
| 3. Multiply         | Each entry: sum of products of row from first and column from second matrix |
| 4. Fill all entries | Repeat for all row/column combinations                                     |

---

**In short:**  
Multiply each row of the 3x3 matrix by each column of the 3x4 matrix, sum the products, and place the result in the corresponding position of the 3x4 product matrix.


resulting shape is (3,3)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### General Formula for the Product

$$
C = A \times B
$$

$$
C_{ij} = \sum_{k=1}^{3} a_{ik} \cdot b_{kj}
$$

Where:
- $i$ = row index (1 to 3)
- $j$ = column index (1 to 4)
- $k$ = index for summing over the shared dimension (1 to 3)

Multiply each row of the 3x3 matrix by each column of the 3x4 matrix, sum the products, and place the result in the corresponding position of the 3x4 product matrix.



In [93]:
import numpy as np

a = np.array([[1,2,3],
               [4,5,6],
              [7,8,9]])

b = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

assert a.shape[1] == b.shape[0]


# create an array of that size


# share Dimentions the same as the rows of the first matrix or columns on the second
sharedDim=a.shape[1]

aRows=a.shape[0]
bColumns=b.shape[1]

# create an empty array with the correct shape
c=np.zeros([a.shape[0],b.shape[1]])

for i in range(aRows):
    for j in range(bColumns):
      # make an accumulator and then plug it into the correct row, column position in c
      print("multiplying a", a[i], "and b", b[:,j])
      cSum = 0
      for k in range(sharedDim):
        cSum += a[i][k] * b[k][j]
      c[i,j]=cSum
    print("\n")

print(c)

print("\nchecking results")

np.dot(a,b)

multiplying a [1 2 3] and b [1 5 9]
multiplying a [1 2 3] and b [ 2  6 10]
multiplying a [1 2 3] and b [ 3  7 11]
multiplying a [1 2 3] and b [ 4  8 12]


multiplying a [4 5 6] and b [1 5 9]
multiplying a [4 5 6] and b [ 2  6 10]
multiplying a [4 5 6] and b [ 3  7 11]
multiplying a [4 5 6] and b [ 4  8 12]


multiplying a [7 8 9] and b [1 5 9]
multiplying a [7 8 9] and b [ 2  6 10]
multiplying a [7 8 9] and b [ 3  7 11]
multiplying a [7 8 9] and b [ 4  8 12]


[[ 38.  44.  50.  56.]
 [ 83.  98. 113. 128.]
 [128. 152. 176. 200.]]

checking results


array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])