<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/neural_network_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# vector (1d)


import numpy as np




arr=np.array([1,2,3])

v=arr

arr,arr.ndim,arr.shape

(array([1, 2, 3]), 1, (3,))

In [2]:
# matric (2d)


# 2 dimensional

arr=np.array([
               [1,2,3],
               [4,5,6]
              ])

d2 = arr

print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)

[[1 2 3]
 [4 5 6]]

ndim 2

shape (2, 3)


In [3]:
# 3d



arr=np.array([
           [
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
          ],
         [
           [1, 2, 3],
           [4, 5, 6],
          [7, 8, 9]
        ],
         [
           [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]
           ]
        ])

d3 = arr

print(arr)
print("\nndim", arr.ndim)
print("\nshape",arr.shape)


# shape: means number of elements in each dimension


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

ndim 3

shape (3, 3, 3)


In [4]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x


In [5]:
print("d2")
print(d2)

print ("\nd2 + d2")
print(d2 + d2)


d2
[[1 2 3]
 [4 5 6]]

d2 + d2
[[ 2  4  6]
 [ 8 10 12]]


# Neural Network Activation Function

In [6]:

def naive_relu(x):
    assert len(x.shape) == 2

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)

    return x




In [7]:
r=naive_relu(d2)
r

array([[1, 2, 3],
       [4, 5, 6]])

# Matrix MUltiplcation

* For 1D arrays (vectors): Returns the standard dot product (a scalar).

* For 2D arrays (matrices): Performs matrix multiplication, i.e., the dot product of rows of the first matrix with columns of the second.

* For higher-dimensional arrays: It performs a sum product over the last axis of the first array and the second-to-last axis of the second array.


## Mutiply vector by 2-d Array

In [8]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]

    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z



##Multiply 2-d Array by 2-d Array

```
d2 = np.array([
        [1 2 3],
        [4 5 6]
        ])

np.dot(d2,d2)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

```



happens because np.dot(d2, d2) tries to perform matrix multiplication, which requires that the number of columns in the first matrix matches the number of rows in the second matrix.

In [9]:
d2_2 = d2.T

print(d2)

print("\n", d2_2, "\n")

np.dot(d2, d2.T)

[[1 2 3]
 [4 5 6]]

 [[1 4]
 [2 5]
 [3 6]] 



array([[14, 32],
       [32, 77]])

# Broadcasting



When two arrays are of different shapes one is broadcast onto another.  That means it is copied to fill the other.

Here illustrate with vector and matrix.

In [14]:

import numpy as np

a = np.array ([1,2,3,4])

b = np.array([
    [1,2,3,4],
    [5,6,7,8]
         ])

# what is a + b?

a + b



array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

See, result is the same when vector is copied.

In [17]:
# same as
import numpy as np

a = np.array ([[1,2,3,4],
              [1,2,3,4]])

b = np.array([
    [1,2,3,4],
    [5,6,7,8]
         ])

# what is a + b?

a + b


array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [19]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

a = np.array ([1,2,3,4])

b = np.array([
    [1,2,3,4],
    [5,6,7,8]
         ])


x=naive_add_matrix_and_vector(b,a)

x

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])