<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/numpy_dimensions_and_arrays_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [161]:
import numpy as np

In [162]:
# a one dimensional array in numpy is like this.

a=np.array([1,2,3])

a

array([1, 2, 3])

In [163]:
# here we ask it how many dimensions it has

a.ndim

1

In [164]:
# here is the shape.  The shape in the number of elements along each dimension
# you can think of this as having one dimension when it puts (3,)

a.shape

(3,)

In [165]:
# if we changed it to this shape it would still have 1 dimension:

a=np.array([[1],[2],[3]])
a.shape

(3, 1)

In [166]:
# that's easier to see if you write it like this

a=np.array([[1],
            [2],
            [3]
            ])

a.shape

(3, 1)

In [167]:
# a two dimension array you can think of as row-column pairs.  We have two outer brackets since
# this is an array of 2-dimensional arrays


b= np.array([
              [1,2],
             [3,4],
             [5,5]
  ])
b

array([[1, 2],
       [3, 4],
       [5, 5]])

In [168]:
# here we have 2 dimensions

b.ndim

2

In [169]:
# the shape is 3 because we have shape (3,2).  this is because there are 3 elements
# in the outer array

b.shape

(3, 2)

In [170]:

# to understand that.  here we have shape (2,3) because we have 2 elements in the outer array.

b= np.array([
              [1,2,3],
             [4,5,6]

  ])

b.shape


# you can also think of axes and dimensions as the same

(2, 3)

In [171]:
# now we will make an array of shape (3,3).  this is an array of 3 elements along each dimension.
# with a three dimensional array we call the third dimension depth.  so we have rows, columns, and depth
# so put another array we will construct an array of 3 rows, 3 columns, and depth of 3

# we can indent this to see this easier.  see that there are 3 2-dimensional arrays

c=np.array([
           [
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
          ],
         [
           [1, 2, 3],
           [4, 5, 6],
          [7, 8, 9]
        ],
         [
           [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]
           ]
        ])

c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [172]:
# there are 3 dimensions

c.ndim

3

In [173]:
# and 3 elements along each dimension.
c.shape

(3, 3, 3)

In [174]:
# first lets make an array of random integers ranging from 0 to 100 with shape (7,7)
# so it will have 49 elements

a = np.random.randint(1,100,(7,7))
a

array([[57, 11, 13, 71, 10, 49, 77],
       [28, 72, 59,  8, 56, 69, 98],
       [74, 84, 37, 50, 97, 35, 68],
       [ 7, 68,  7, 63, 21, 72,  8],
       [47, 72, 43, 59, 13, 53, 40],
       [ 6, 35,  9, 51, 90, 83, 30],
       [19, 96, 42,  9, 91, 22, 57]])

In [175]:
# now we show how to do slicing.  the general format for a 2x2 array is

# a[from : to -1 , from : to -1]

# the colon by itself means all elements, like a[:,:]

# so the comma seperates the axis and the colon says what to do within the axis


# first columns from the 4th and 5th rows
# remember we start counting array elements at 0 so we write 3 when we mean element 4

a[3:5,:]


array([[ 7, 68,  7, 63, 21, 72,  8],
       [47, 72, 43, 59, 13, 53, 40]])

In [176]:
# now get all rows from the 4th and 5th column
a[:,3:5]

array([[71, 10],
       [ 8, 56],
       [50, 97],
       [63, 21],
       [59, 13],
       [51, 90],
       [ 9, 91]])

In [177]:
# make 16 elements raning from 1 to 16

a=np.linspace(1,16,16)

# this would be the same as writing

a=np.linspace(1,16,16,(16,))

a.shape


(16,)

In [178]:
# here we show how to print every other element.

# so the format is [from : to : step]

a[0:4:2]

array([1., 3.])

In [179]:
# here we show that y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d]

# first let's make the array have 2 dimensions using reshape.  we have 16 elements
# which w can divide into 4 rows and 4 columns

a=a.reshape(4,4).astype(np.int8)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [180]:
# lets print the 2nd and 3rd row item from the 2rd and 3rd column

a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]], dtype=int8)

In [181]:
# now we can get the same results using two sets of brackets. think of that
# as doing two operations:  slice and then slice again
# the it is easier to understand

a[1:3,:][:,1:3]

array([[ 6,  7],
       [10, 11]], dtype=int8)

In [182]:
# the asterisk is short-hand for 0:

# so a[0:5] is the same as a[*5]

print(a[0:5])

print("\n")

print(a[:5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [183]:
# a negative sign means go backwards from the end moving to the left

b = np.array([10, 20, 30, 40, 50, 60, 70, 80])

b[-4]


50

In [184]:
# let's think about our 3 dimensional array again
#first print it so we can it see again

c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [185]:
# now, this gets the first row element in each of the 3 arrays
c[:,0,0]

array([1, 1, 1])

In [186]:
# this gets the all the rows and columns in the first 2d array at depth 0

c[:,:,0]

array([[1, 4, 7],
       [1, 4, 7],
       [1, 4, 7]])

In [187]:
# this gets the first element in the 3d array.  so it is the first element in the first row,
# in the first column, in the first depth

c[0,0,0]

1