<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/numpy_dimensions_and_arrays_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> **Video that goes with this Tutorial**
>
> [Here is the video that goes with this tutorial](https://www.youtube.com/watch?v=CgA0EQjkxlk)


# Other Tutorials
|   |   |
| --- | --- |  
| [Python Basics](#python-basics) |  [Algorithms](#algorithms) |
| [Pandas](#pandas) |  [Numpy](#numpy) |  
| [Statistics](#statistics)  | [Charting](#charting) |
| [Linear and Logistic Regression](#linear-and-logistic-regression) | [Data Science Analysis](#data-science-analysis) |
| [Games](#games) | [Python Certification](python-certification) |   

In [ ]:
import numpy as np

In [ ]:
# a one dimensional array in numpy is like this.

a=np.array([1,2,3])

a

array([1, 2, 3])

In [ ]:
# here we ask it how many dimensions it has

a.ndim

1

In [ ]:
# here is the shape.  The shape in the number of elements along each dimension
# you can think of this as having one dimension when it puts (3,)

a.shape

(3,)

In [ ]:
# if we changed it to this shape it would still have 1 dimension:

a=np.array([[1],[2],[3]])
a.shape

(3, 1)

In [ ]:
# that's easier to see if you write it like this

a=np.array([[1],
            [2],
            [3]
            ])

a.shape

(3, 1)

In [ ]:
# a two dimension array you can think of as row-column pairs.  We have two outer brackets since
# this is an array of 2-dimensional arrays


b= np.array([
              [1,2],
             [3,4],
             [5,5]
  ])
b

array([[1, 2],
       [3, 4],
       [5, 5]])

In [ ]:
# here we have 2 dimensions

b.ndim

2

In [ ]:
# the shape is 3 because we have shape (3,2).  this is because there are 3 elements
# in the outer array

b.shape

(3, 2)

In [ ]:

# to understand that.  here we have shape (2,3) because we have 2 elements in the outer array.

b= np.array([
              [1,2,3],
             [4,5,6]

  ])

b.shape


# you can also think of axes and dimensions as the same

(2, 3)

In [ ]:
# now we will make an array of shape (3,3).  this is an array of 3 elements along each dimension.
# with a three dimensional array we call the third dimension depth.  so we have rows, columns, and depth
# so put another array we will construct an array of 3 rows, 3 columns, and depth of 3

# we can indent this to see this easier.  see that there are 3 2-dimensional arrays

c=np.array([
           [
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
          ],
         [
           [1, 2, 3],
           [4, 5, 6],
          [7, 8, 9]
        ],
         [
           [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]
           ]
        ])

c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
# there are 3 dimensions

c.ndim

3

In [ ]:
# and 3 elements along each dimension.
c.shape

(3, 3, 3)

In [ ]:
# first lets make an array of random integers ranging from 0 to 100 with shape (7,7)
# so it will have 49 elements

a = np.random.randint(1,100,(7,7))
a

array([[10, 23, 34, 29, 38, 80, 40],
       [58, 97, 99,  9, 52, 76, 38],
       [50, 54, 63, 39, 92, 49, 98],
       [16, 64, 98,  3, 80, 27, 88],
       [64,  7, 20, 42, 92, 59, 91],
       [75, 92, 80, 63, 38, 43, 52],
       [61, 99, 45, 10, 55, 70, 67]])

In [ ]:
# now we show how to do slicing.  the general format for a 2x2 array is

# a[from : to -1 , from : to -1]

# the colon by itself means all elements, like a[:,:]

# so the comma seperates the axis and the colon says what to do within the axis


# first columns from the 4th and 5th rows
# remember we start counting array elements at 0 so we write 3 when we mean element 4

a[3:5,:]


array([[16, 64, 98,  3, 80, 27, 88],
       [64,  7, 20, 42, 92, 59, 91]])

In [ ]:
# now get all rows from the 4th and 5th column
a[:,3:5]

array([[29, 38],
       [ 9, 52],
       [39, 92],
       [ 3, 80],
       [42, 92],
       [63, 38],
       [10, 55]])

In [ ]:
# make 16 elements raning from 1 to 16

a=np.linspace(1,16,16)

# this would be the same as writing

a=np.linspace(1,16,16,(16,))

a.shape


(16,)

In [ ]:
# here we show how to print every other element.

# so the format is [from : to : step]

a[0:4:2]

array([1., 3.])

In [ ]:
# here we show that y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d]

# first let's make the array have 2 dimensions using reshape.  we have 16 elements
# which w can divide into 4 rows and 4 columns

a=a.reshape(4,4).astype(np.int8)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [ ]:
# lets print the 2nd and 3rd row item from the 2rd and 3rd column

a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]], dtype=int8)

In [ ]:
# now we can get the same results using two sets of brackets. think of that
# as doing two operations:  slice and then slice again
# the it is easier to understand

a[1:3,:][:,1:3]

array([[ 6,  7],
       [10, 11]], dtype=int8)

In [ ]:
# the asterisk is short-hand for 0:

# so a[0:5] is the same as a[*5]

print(a[0:5])

print("\n")

print(a[:5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# a negative sign means go backwards from the end moving to the left

b = np.array([10, 20, 30, 40, 50, 60, 70, 80])

b[-4]


50

In [ ]:
# let's think about our 3 dimensional array again
#first print it so we can it see again

c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
# the slice operation on the array c is over (depth, row, column)

# now, this gets the first row and column is each of the outermost array,
# i.e., the one measured by depth

c[:,0,0]

array([1, 1, 1])

In [ ]:
# this all rows in the first column from each of the 3 outer arrays, i.e., depth


c[:,:,0]

array([[1, 4, 7],
       [1, 4, 7],
       [1, 4, 7]])

In [ ]:
# this gets the first element in the 3d array.  so it is the first element in the first depth,
# row, and column

c[0,0,0]

1