<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/numpy/numpy_tutorial_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/devdocs/user/quickstart.html


In [18]:
import numpy as np

arr=np.array([[2,1,4],
              [2,1,4],
              [3,4,5]],dtype=np.int16)



In [16]:
#dimensions

arr.shape


(3, 3)

In [19]:
#axes.  why is this not 3?

arr.ndim

2

In [23]:
# this creates an array of 15 elements

a = np.arange(15)
b = np.ones(15,dtype=np.int16)
c = np.zeros(15)
print(a)
print(b)
print(c)


 #.reshape(3, 5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
 # a vector has one column.  a matrix has more than one column

 # since this has 15 rows.  we can divides into 3 * 5

 a.shape

(15,)

In [30]:
 g=a.reshape(3,5)
 print("shape=", g.shape)
 print("axes=", g.ndim)
 print(g)

shape= (3, 5)
axes= 2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [31]:
# this will produce an error because you can't fit 15 items into 12 places.

# shape 3x4 is 3 rows and 4 columns
a.reshape(3,4)

ValueError: ignored

In [32]:
# let's use floating point numbers

# it means it has a decimal point

b = np.array([1.2, 3.5, 5.1])


In [33]:
# one issue with computers is you cannot represent real numbers

# for example the real number 3.333333.....   goes on forever

# but the computer cannot do that.  it has to stop at a certain number of digits

# 3.3333333333333333333 - 3.333333333 > 0


floatingNumber=3.333333

In [34]:
# this wrong because arrays have [] brackets.  functions have parantheses ()

# a = np.array(1, 2, 3, 4)    # WRONG

a = np.array([1, 2, 3, 4]) # correct


In [36]:
#  a tuple is a list of items .  the only difference between a tuple
# and a list if you cannot change items in a tuple

l = [1,2,3]
l[1]=4

t=(1.5, 2, 3)

In [35]:
# what the documentation is saying is that if you use a tuple it will convert it
# to an array.  meaning tuples don't exist in numpy


b = np.array([(1.5, 2, 3), (4, 5, 6)])



In [38]:
# take what is in memory now and make an array out of it.  so it
# will just be junk.  not very useful


np.empty((2, 3))


array([[4.31133145e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [42]:
np.linspace(1, 9, 3)


array([1., 5., 9.])

In [44]:
# Tamara thing about this.  This creates number evenly distributed over some range


np.linspace(3,15,5)

# we want 3, 6, 9, 12, 15


array([ 3.,  6.,  9., 12., 15.])

In [43]:
# here we tell it to make an array.  we say start at 2 and then evenly space
# out 4 elements ending at 8


np.linspace(2, 8, 4)

array([2., 4., 6., 8.])

In [41]:
# the arguments for line space and start, stop, and how many.  the default for how many is 50
np.linspace(1, 50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [45]:
# regular python

import random

random.random()


0.35133271918870523

In [46]:
# if you don't give it size it creates a float

# a float just means a decimal number


np.random.random()


0.05840291115082186

In [50]:
# create a 3x2 array

np.random.random([3,2])

array([[0.05598569, 0.28640392],
       [0.28812199, 0.94024105],
       [0.64684101, 0.83610496]])